// Code generated by giraffe-go. DO NOT EDIT.
package validators

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"reflect"
	"strconv"

	"go.easyops.local/fintech_data/internal/apierrors"

	"github.com/asaskevich/govalidator"
	"github.com/gin-gonic/gin"
	types "github.com/gogo/protobuf/types"

	giraffe_validators "go.easyops.local/giraffe/pkg/validators"
	"go.easyops.local/kit/gogoprotobuf/jsonpb"
	"go.easyops.local/kit/protobuf/protostruct"
	logctx "go.easyops.local/slog/context"

	message "go.easyops.local/contracts/protorepo-fintech_data/fill_instance"
)

var _ = gin.Bind
var _ = logctx.MustGetLogger
var _ = apierrors.ErrAborted
var _ = fmt.Printf
var _ = errors.New
var _ = bytes.Compare
var _ = strconv.Atoi
var _ = govalidator.Matches
var _ = json.Marshal
var _ = jsonpb.Marshaler{}
var _ = protostruct.ToStruct
var _ = reflect.ValueOf
var _ = types.Struct{}
var _ = giraffe_validators.ValidateConstraints

func ValidateInstanceCallback(ctx *gin.Context) (*message.InstanceCallbackRequest, error) {
	logger := logctx.MustGetLogger(ctx.Request.Context())
	var _ = logger

	request := &message.InstanceCallbackRequest{}
	var err error

	jsonpbUnmarshaler := jsonpb.Unmarshaler{}
	var buf []byte
	buf, err = ctx.GetRawData()
	if err != nil {
		logger.Errorf("get raw data error, e=%s", err.Error())
		return nil, apierrors.NewErrorInvalidArgument(fmt.Sprintf("获取body数据失败，错误详情:%s", err.Error()))
	}
	// POST, PATCH, PUT请求
	buf, err = giraffe_validators.ValidatePostRequiredAndSetDefault(ctx, buf,
		[]string{},
		map[string]interface{}{},
		InstanceCallbackValidateTree,
	)
	if err != nil {
		logger.Errorf("jsonpb unmarshal error, e=%s", err.Error())
		return nil, err
	}
	if len(buf) > 0 {
		err = jsonpbUnmarshaler.UnmarshalFromString(string(buf), request)

		if err != nil {
			logger.Errorf("jsonpb unmarshal error, e=%s", err.Error())
			return nil, apierrors.NewErrorInvalidArgument(fmt.Sprintf("json解析失败，错误详情:%s", err.Error()))
		}
	}
	return request, err
}
