type: simple-script
name: 动环监控
version: "1769673511"
command:
    collect:
        interpreter: ""
        scriptPath:
            - src
            - 动环监控.py
        type: python
        user: ""
params:
    - ip
    - port
    - community
    - username
    - auth_key
    - auth_protocol
    - priv_key
    - priv_protocol
    - version
    - monitor_point_path
    - singl_point_oid
paramDefine:
    - name: ip
      valueType: string
      defaultValue: ""
      display: true
      displayName: ""
      description: ""
      use: collectParams
      optional: false
      isFromSecret: false
      isEncrypt: false
      extraArgs: null
    - name: port
      valueType: string
      defaultValue: "161"
      display: true
      displayName: ""
      description: ""
      use: collectParams
      optional: false
      isFromSecret: false
      isEncrypt: false
      extraArgs: null
    - name: community
      valueType: string
      defaultValue: public
      display: true
      displayName: ""
      description: ""
      use: collectParams
      optional: true
      isFromSecret: false
      isEncrypt: false
      extraArgs: null
    - name: username
      valueType: string
      defaultValue: ""
      display: true
      displayName: ""
      description: ""
      use: collectParams
      optional: true
      isFromSecret: false
      isEncrypt: false
      extraArgs: null
    - name: auth_key
      valueType: string
      defaultValue: ""
      display: true
      displayName: ""
      description: ""
      use: collectParams
      optional: true
      isFromSecret: false
      isEncrypt: false
      extraArgs: null
    - name: auth_protocol
      valueType: string
      defaultValue: ""
      display: true
      displayName: ""
      description: ""
      use: collectParams
      optional: true
      isFromSecret: false
      isEncrypt: false
      extraArgs: null
    - name: priv_key
      valueType: string
      defaultValue: ""
      display: true
      displayName: ""
      description: ""
      use: collectParams
      optional: true
      isFromSecret: false
      isEncrypt: false
      extraArgs: null
    - name: priv_protocol
      valueType: string
      defaultValue: ""
      display: true
      displayName: ""
      description: ""
      use: collectParams
      optional: true
      isFromSecret: false
      isEncrypt: false
      extraArgs: null
    - name: version
      valueType: string
      defaultValue: 2c
      display: true
      displayName: ""
      description: ""
      use: collectParams
      optional: false
      isFromSecret: false
      isEncrypt: false
      extraArgs: null
    - name: monitor_point_path
      valueType: string
      defaultValue: $.monitor_point_path
      display: true
      displayName: ""
      description: ""
      use: collectParams
      optional: false
      isFromSecret: false
      isEncrypt: false
      extraArgs: null
    - name: singl_point_oid
      valueType: string
      defaultValue: $.singl_point_oid
      display: true
      displayName: ""
      description: ""
      use: collectParams
      optional: false
      isFromSecret: false
      isEncrypt: false
      extraArgs: null
agentType: easyops
category: 硬件相关
scriptType: python
interpreter: ""
memo: ""
icon: null
relateObjectId: ENV_MONITOR_SYSTEM_MONITOR_POINTS
installPath: 动环监控
samplerType: metric_sampler
jobFilter: null
protected: false
noPackage: false
collectType: []
collectAgent: ""
group: []
rating: 0
metricbeatName: ""
processors: []
extInfo: null
