// Code generated by giraffe-go. DO NOT EDIT.
package task

import (
	"github.com/gin-gonic/gin"
	types "github.com/gogo/protobuf/types"

	message "go.easyops.local/contracts/protorepo-fintech_data/task"
	"go.easyops.local/fintech_data/internal/apierrors"
	"go.easyops.local/fintech_data/task/validators"
	"go.easyops.local/kit/gerr"
	kitweb "go.easyops.local/kit/web"
	"go.easyops.local/slog"
	logctx "go.easyops.local/slog/context"
)

var _ kitweb.JSONPb
var _ = apierrors.ErrInvalidArgument
var _ = types.Struct{}
var _ = validators.EmptyTree

type TaskController struct {
	logger  slog.Logger
	service TaskService
}

func NewTaskController(logger slog.Logger, service TaskService) *TaskController {
	return &TaskController{
		logger:  logger,
		service: service,
	}
}

func (s *TaskController) DebugToken(ctx *gin.Context) {
	logger := logctx.MustGetLogger(ctx.Request.Context())
	var _ = logger
	var err error

	request, err := validators.ValidateDebugToken(ctx)
	if err != nil {
		apiError := gerr.ToApiError(err)
		ctx.JSON(apiError.Status(), apiError.Data())
		return
	}

	data, err := s.service.DebugToken(ctx.Request.Context(), request)
	if err != nil {
		apiError := gerr.ToApiError(err)
		ctx.JSON(apiError.Status(), apiError.Data())
		return
	} else {

		ctx.Render(200, kitweb.JSONPb{
			Data: &message.DebugTokenResponseWrapper{
				Data: data,
			},
			UseCustomMarshaler: true,
			UseGogo:            true,
		})
		return

	}
}

func (s *TaskController) GetGlobalConfig(ctx *gin.Context) {
	logger := logctx.MustGetLogger(ctx.Request.Context())
	var _ = logger
	var err error

	request := &types.Empty{}

	data, err := s.service.GetGlobalConfig(ctx.Request.Context(), request)
	if err != nil {
		apiError := gerr.ToApiError(err)
		ctx.JSON(apiError.Status(), apiError.Data())
		return
	} else {

		ctx.Render(200, kitweb.JSONPb{
			Data: &message.GetGlobalConfigResponseWrapper{
				Data: data,
			},
			UseCustomMarshaler: true,
			UseGogo:            true,
		})
		return

	}
}

func (s *TaskController) ReportData(ctx *gin.Context) {
	logger := logctx.MustGetLogger(ctx.Request.Context())
	var _ = logger
	var err error

	request, err := validators.ValidateReportData(ctx)
	if err != nil {
		apiError := gerr.ToApiError(err)
		ctx.JSON(apiError.Status(), apiError.Data())
		return
	}

	data, err := s.service.ReportData(ctx.Request.Context(), request)
	if err != nil {
		apiError := gerr.ToApiError(err)
		ctx.JSON(apiError.Status(), apiError.Data())
		return
	} else {

		ctx.Render(200, kitweb.JSONPb{
			Data: &message.ReportDataResponseWrapper{
				Data: data,
			},
			UseCustomMarshaler: true,
			UseGogo:            true,
		})
		return

	}
}

func (s *TaskController) RequestAudit(ctx *gin.Context) {
	logger := logctx.MustGetLogger(ctx.Request.Context())
	var _ = logger
	var err error

	request, err := validators.ValidateRequestAudit(ctx)
	if err != nil {
		apiError := gerr.ToApiError(err)
		ctx.JSON(apiError.Status(), apiError.Data())
		return
	}

	data, err := s.service.RequestAudit(ctx.Request.Context(), request)
	if err != nil {
		apiError := gerr.ToApiError(err)
		ctx.JSON(apiError.Status(), apiError.Data())
		return
	} else {

		ctx.Render(200, kitweb.JSONPb{
			Data: &message.RequestAuditResponseWrapper{
				Data: data,
			},
			UseCustomMarshaler: true,
			UseGogo:            true,
		})
		return

	}
}

func (s *TaskController) UpdateGlobalConfig(ctx *gin.Context) {
	logger := logctx.MustGetLogger(ctx.Request.Context())
	var _ = logger
	var err error

	request, err := validators.ValidateUpdateGlobalConfig(ctx)
	if err != nil {
		apiError := gerr.ToApiError(err)
		ctx.JSON(apiError.Status(), apiError.Data())
		return
	}

	data, err := s.service.UpdateGlobalConfig(ctx.Request.Context(), request)
	if err != nil {
		apiError := gerr.ToApiError(err)
		ctx.JSON(apiError.Status(), apiError.Data())
		return
	} else {

		ctx.Render(200, kitweb.JSONPb{
			Data: &message.UpdateGlobalConfigResponseWrapper{
				Data: data,
			},
			UseCustomMarshaler: true,
			UseGogo:            true,
		})
		return

	}
}
