// Code generated by giraffe-go. DO NOT EDIT.
package task

import "github.com/gin-gonic/gin"

func (s *TaskController) Register(engine *gin.Engine) {
	engine.POST("/api/debug/token", s.DebugToken)
	engine.GET("/api/global/config", s.GetGlobalConfig)
	engine.POST("/api/report/data", s.ReportData)
	engine.POST("/api/report/branch/audit", s.RequestAudit)
	engine.PUT("/api/global/config", s.UpdateGlobalConfig)
}
