// Code generated by giraffe-go. DO NOT EDIT.
package task

import (
	message "go.easyops.local/contracts/protorepo-fintech_data/task"

	"context"
	"io"
	"mime/multipart"

	"github.com/gin-gonic/gin/render"
	types "github.com/gogo/protobuf/types"

	"go.easyops.local/contracts/protorepo-models/easyops/model/fintech_data"
)

var _ = render.WriteJSON
var _ = multipart.NewReader
var _ = io.Copy
var _ = types.Struct{}
var _ = message.NewClient

type TaskService interface {
	DebugToken(ctx context.Context, request *message.DebugTokenRequest) (*message.DebugTokenResponse, error)
	GetGlobalConfig(ctx context.Context, request *types.Empty) (*fintech_data.ReportGlobalConfig, error)
	ReportData(ctx context.Context, request *message.ReportDataRequest) (*message.ReportDataResponse, error)
	RequestAudit(ctx context.Context, request *message.RequestAuditRequest) (*types.Empty, error)
	UpdateGlobalConfig(ctx context.Context, request *fintech_data.ReportGlobalConfig) (*types.Empty, error)
}
