// Code generated by MockGen. DO NOT EDIT.
// Source: go.easyops.local/contracts/protorepo-notify/oplog (interfaces: Client)

// Package notify is a generated GoMock package.
package notify

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	notify "go.easyops.local/contracts/protorepo-models/easyops/model/notify"
	oplog "go.easyops.local/contracts/protorepo-notify/oplog"
)

// MockOpLogClient is a mock of Client interface
type MockOpLogClient struct {
	ctrl     *gomock.Controller
	recorder *MockOpLogClientMockRecorder
}

// MockOpLogClientMockRecorder is the mock recorder for MockOpLogClient
type MockOpLogClientMockRecorder struct {
	mock *MockOpLogClient
}

// NewMockOpLogClient creates a new mock instance
func NewMockOpLogClient(ctrl *gomock.Controller) *MockOpLogClient {
	mock := &MockOpLogClient{ctrl: ctrl}
	mock.recorder = &MockOpLogClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockOpLogClient) EXPECT() *MockOpLogClientMockRecorder {
	return m.recorder
}

// CreateOperationLog mocks base method
func (m *MockOpLogClient) CreateOperationLog(arg0 context.Context, arg1 *notify.OperationLogWithMeta) (*oplog.CreateOperationLogResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOperationLog", arg0, arg1)
	ret0, _ := ret[0].(*oplog.CreateOperationLogResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOperationLog indicates an expected call of CreateOperationLog
func (mr *MockOpLogClientMockRecorder) CreateOperationLog(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOperationLog", reflect.TypeOf((*MockOpLogClient)(nil).CreateOperationLog), arg0, arg1)
}

// ListOperationLog mocks base method
func (m *MockOpLogClient) ListOperationLog(arg0 context.Context, arg1 *notify.ListOperationLogRequest) (*oplog.ListOperationLogResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOperationLog", arg0, arg1)
	ret0, _ := ret[0].(*oplog.ListOperationLogResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOperationLog indicates an expected call of ListOperationLog
func (mr *MockOpLogClientMockRecorder) ListOperationLog(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOperationLog", reflect.TypeOf((*MockOpLogClient)(nil).ListOperationLog), arg0, arg1)
}
