// Code generated by MockGen. DO NOT EDIT.
// Source: go.easyops.local/contracts/protorepo-notify/subscriber (interfaces: Client)

// Package notify is a generated GoMock package.
package notify

import (
	context "context"
	reflect "reflect"

	types "github.com/gogo/protobuf/types"
	gomock "github.com/golang/mock/gomock"

	notify "go.easyops.local/contracts/protorepo-models/easyops/model/notify"
)

// MockSubscriberClient is a mock of Client interface
type MockSubscriberClient struct {
	ctrl     *gomock.Controller
	recorder *MockSubscriberClientMockRecorder
}

// MockSubscriberClientMockRecorder is the mock recorder for MockSubscriberClient
type MockSubscriberClientMockRecorder struct {
	mock *MockSubscriberClient
}

// NewMockSubscriberClient creates a new mock instance
func NewMockSubscriberClient(ctrl *gomock.Controller) *MockSubscriberClient {
	mock := &MockSubscriberClient{ctrl: ctrl}
	mock.recorder = &MockSubscriberClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockSubscriberClient) EXPECT() *MockSubscriberClientMockRecorder {
	return m.recorder
}

// CreateSubscriber mocks base method
func (m *MockSubscriberClient) CreateSubscriber(arg0 context.Context, arg1 *notify.Subscriber) (*types.Empty, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSubscriber", arg0, arg1)
	ret0, _ := ret[0].(*types.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSubscriber indicates an expected call of CreateSubscriber
func (mr *MockSubscriberClientMockRecorder) CreateSubscriber(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSubscriber", reflect.TypeOf((*MockSubscriberClient)(nil).CreateSubscriber), arg0, arg1)
}
