// Code generated by giraffe-go. DO NOT EDIT.
package history

import (
	"github.com/gin-gonic/gin"
	types "github.com/gogo/protobuf/types"
	message "go.easyops.local/contracts/protorepo-fintech_data/history"
	"go.easyops.local/fintech_data/history/validators"
	"go.easyops.local/fintech_data/internal/apierrors"
	"go.easyops.local/kit/gerr"
	kitweb "go.easyops.local/kit/web"
	"go.easyops.local/slog"
	logctx "go.easyops.local/slog/context"
)

var _ kitweb.JSONPb
var _ = apierrors.ErrInvalidArgument
var _ = types.Struct{}
var _ = validators.EmptyTree

type HistoryController struct {
	logger  slog.Logger
	service HistoryService
}

func NewHistoryController(logger slog.Logger, service HistoryService) *HistoryController {
	return &HistoryController{
		logger:  logger,
		service: service,
	}
}

func (s *HistoryController) ExportReportTask(ctx *gin.Context) {
	logger := logctx.MustGetLogger(ctx.Request.Context())
	var _ = logger
	var err error

	request, err := validators.ValidateExportReportTask(ctx)
	if err != nil {
		apiError := gerr.ToApiError(err)
		ctx.JSON(apiError.Status(), apiError.Data())
		return
	}

	builder, err := s.service.ExportReportTask(ctx.Request.Context(), request)
	if err != nil {
		apiError := gerr.ToApiError(err)
		ctx.JSON(apiError.Status(), apiError.Data())
		return
	} else {
		builder.SetHeader(ctx)
		builder.Write(ctx.Writer)
		return
	}
}

func (s *HistoryController) ExportReportInstance(ctx *gin.Context) {
	logger := logctx.MustGetLogger(ctx.Request.Context())
	var _ = logger
	var err error

	request, err := validators.ValidateExportReportInstance(ctx)
	if err != nil {
		apiError := gerr.ToApiError(err)
		ctx.JSON(apiError.Status(), apiError.Data())
		return
	}

	builder, err := s.service.ExportReportInstance(ctx.Request.Context(), request)
	if err != nil {
		apiError := gerr.ToApiError(err)
		ctx.JSON(apiError.Status(), apiError.Data())
		return
	} else {
		builder.SetHeader(ctx)
		builder.Write(ctx.Writer)
		return
	}
}

func (s *HistoryController) GetReportInstanceTotal(ctx *gin.Context) {
	logger := logctx.MustGetLogger(ctx.Request.Context())
	var _ = logger
	var err error

	request, err := validators.ValidateGetReportInstanceTotal(ctx)
	if err != nil {
		apiError := gerr.ToApiError(err)
		ctx.JSON(apiError.Status(), apiError.Data())
		return
	}

	data, err := s.service.GetReportInstanceTotal(ctx.Request.Context(), request)
	if err != nil {
		apiError := gerr.ToApiError(err)
		ctx.JSON(apiError.Status(), apiError.Data())
		return
	} else {

		ctx.Render(200, kitweb.JSONPb{
			Data: &message.GetReportInstanceTotalResponseWrapper{
				Data: data,
			},
			UseCustomMarshaler: true,
			UseGogo:            true,
		})
		return

	}
}

func (s *HistoryController) GetReportTask(ctx *gin.Context) {
	logger := logctx.MustGetLogger(ctx.Request.Context())
	var _ = logger
	var err error

	request, err := validators.ValidateGetReportTask(ctx)
	if err != nil {
		apiError := gerr.ToApiError(err)
		ctx.JSON(apiError.Status(), apiError.Data())
		return
	}

	data, err := s.service.GetReportTask(ctx.Request.Context(), request)
	if err != nil {
		apiError := gerr.ToApiError(err)
		ctx.JSON(apiError.Status(), apiError.Data())
		return
	} else {

		ctx.Render(200, kitweb.JSONPb{
			Data: &message.GetReportTaskResponseWrapper{
				Data: data,
			},
			UseCustomMarshaler: true,
			UseGogo:            true,
		})
		return

	}
}

func (s *HistoryController) LastReportTask(ctx *gin.Context) {
	logger := logctx.MustGetLogger(ctx.Request.Context())
	var _ = logger
	var err error

	request, err := validators.ValidateLastReportTask(ctx)
	if err != nil {
		apiError := gerr.ToApiError(err)
		ctx.JSON(apiError.Status(), apiError.Data())
		return
	}

	data, err := s.service.LastReportTask(ctx.Request.Context(), request)
	if err != nil {
		apiError := gerr.ToApiError(err)
		ctx.JSON(apiError.Status(), apiError.Data())
		return
	} else {

		ctx.Render(200, kitweb.JSONPb{
			Data: &message.LastReportTaskResponseWrapper{
				Data: data,
			},
			UseCustomMarshaler: true,
			UseGogo:            true,
		})
		return

	}
}

func (s *HistoryController) SearchReportBranch(ctx *gin.Context) {
	logger := logctx.MustGetLogger(ctx.Request.Context())
	var _ = logger
	var err error

	request, err := validators.ValidateSearchReportBranch(ctx)
	if err != nil {
		apiError := gerr.ToApiError(err)
		ctx.JSON(apiError.Status(), apiError.Data())
		return
	}

	data, err := s.service.SearchReportBranch(ctx.Request.Context(), request)
	if err != nil {
		apiError := gerr.ToApiError(err)
		ctx.JSON(apiError.Status(), apiError.Data())
		return
	} else {

		ctx.Render(200, kitweb.JSONPb{
			Data: &message.SearchReportBranchResponseWrapper{
				Data: data,
			},
			UseCustomMarshaler: true,
			UseGogo:            true,
		})
		return

	}
}

func (s *HistoryController) HandleReportInstance(ctx *gin.Context) {
	logger := logctx.MustGetLogger(ctx.Request.Context())
	var _ = logger
	var err error

	request, err := validators.ValidateHandleReportInstance(ctx)
	if err != nil {
		apiError := gerr.ToApiError(err)
		ctx.JSON(apiError.Status(), apiError.Data())
		return
	}

	err = s.service.HandleReportInstance(ctx.Request.Context(), request)
	if err != nil {
		apiError := gerr.ToApiError(err)
		ctx.JSON(apiError.Status(), apiError.Data())
		return
	} else {
		ctx.Render(200, kitweb.JSONPb{
			Data:               &message.HandlReportInstanceResponseWrapper{},
			UseCustomMarshaler: true,
			UseGogo:            true,
		})
		return

	}
}

func (s *HistoryController) SearchReportInstance(ctx *gin.Context) {
	logger := logctx.MustGetLogger(ctx.Request.Context())
	var _ = logger
	var err error

	request, err := validators.ValidateSearchReportInstance(ctx)
	if err != nil {
		apiError := gerr.ToApiError(err)
		ctx.JSON(apiError.Status(), apiError.Data())
		return
	}

	data, err := s.service.SearchReportInstance(ctx.Request.Context(), request)
	if err != nil {
		apiError := gerr.ToApiError(err)
		ctx.JSON(apiError.Status(), apiError.Data())
		return
	} else {

		ctx.Render(200, kitweb.JSONPb{
			Data: &message.SearchReportInstanceResponseWrapper{
				Data: data,
			},
			UseCustomMarshaler: true,
			UseGogo:            true,
		})
		return

	}
}

func (s *HistoryController) SearchReportTask(ctx *gin.Context) {
	logger := logctx.MustGetLogger(ctx.Request.Context())
	var _ = logger
	var err error

	request, err := validators.ValidateSearchReportTask(ctx)
	if err != nil {
		apiError := gerr.ToApiError(err)
		ctx.JSON(apiError.Status(), apiError.Data())
		return
	}

	data, err := s.service.SearchReportTask(ctx.Request.Context(), request)
	if err != nil {
		apiError := gerr.ToApiError(err)
		ctx.JSON(apiError.Status(), apiError.Data())
		return
	} else {

		ctx.Render(200, kitweb.JSONPb{
			Data: &message.SearchReportTaskResponseWrapper{
				Data: data,
			},
			UseCustomMarshaler: true,
			UseGogo:            true,
		})
		return

	}
}
