// Code generated by giraffe-go. DO NOT EDIT.
package history

import "github.com/gin-gonic/gin"

func (s *HistoryController) Register(engine *gin.Engine) {
	engine.POST("/api/report/instance/export", s.ExportReportInstance)
	engine.POST("/api/report/task/export", s.ExportReportTask)
	engine.GET("/api/report/instance/total", s.GetReportInstanceTotal)
	engine.GET("/api/report/task/:taskId", s.GetReportTask)
	engine.POST("/api/report/instance/handle", s.HandleReportInstance)
	engine.GET("/api/last/report/task", s.LastReportTask)
	engine.POST("/api/report/branch/_search", s.SearchReportBranch)
	engine.POST("/api/report/instance/_search", s.SearchReportInstance)
	engine.POST("/api/report/task/_search", s.SearchReportTask)
}
