// Code generated by giraffe-go. DO NOT EDIT.
package history

import (
	message "go.easyops.local/contracts/protorepo-fintech_data/history"
	internaltypes "go.easyops.local/fintech_data/internal/types"

	"context"
	"github.com/gin-gonic/gin/render"
	types "github.com/gogo/protobuf/types"
	"go.easyops.local/contracts/protorepo-models/easyops/model/fintech_data"
	"io"
	"mime/multipart"
)

var _ = render.WriteJSON
var _ = multipart.NewReader
var _ = io.Copy
var _ = types.Struct{}
var _ = message.NewClient

type HistoryService interface {
	ExportReportInstance(ctx context.Context, request *message.ExportReportInstanceRequest) (internaltypes.FileExporter, error)
	ExportReportTask(ctx context.Context, request *message.ExportReportTaskRequest) (internaltypes.FileExporter, error)
	GetReportInstanceTotal(ctx context.Context, request *message.GetReportInstanceTotalRequest) (*message.GetReportInstanceTotalResponse, error)
	GetReportTask(ctx context.Context, request *message.GetReportTaskRequest) (*fintech_data.ReportTask, error)
	LastReportTask(ctx context.Context, request *message.LastReportTaskRequest) (*fintech_data.ReportTask, error)
	SearchReportBranch(ctx context.Context, request *message.SearchReportBranchRequest) (*message.SearchReportBranchResponse, error)
	SearchReportInstance(ctx context.Context, request *message.SearchReportInstanceRequest) (*message.SearchReportInstanceResponse, error)
	SearchReportTask(ctx context.Context, request *message.SearchReportTaskRequest) (*message.SearchReportTaskResponse, error)
	HandleReportInstance(ctx context.Context, request *message.HandlReportInstanceRequest) error
}
