// Code generated by MockGen. DO NOT EDIT.
// Source: go.easyops.local/contracts/protorepo-user_service/organization (interfaces: Client)

// Package user_service is a generated GoMock package.
package user_service

import (
	context "context"
	reflect "reflect"

	types "github.com/gogo/protobuf/types"
	gomock "github.com/golang/mock/gomock"

	user_service "go.easyops.local/contracts/protorepo-models/easyops/model/user_service"
	organization "go.easyops.local/contracts/protorepo-user_service/organization"
)

// MockOrgClient is a mock of Client interface
type MockOrgClient struct {
	ctrl     *gomock.Controller
	recorder *MockOrgClientMockRecorder
}

// MockOrgClientMockRecorder is the mock recorder for MockOrgClient
type MockOrgClientMockRecorder struct {
	mock *MockOrgClient
}

// NewMockOrgClient creates a new mock instance
func NewMockOrgClient(ctrl *gomock.Controller) *MockOrgClient {
	mock := &MockOrgClient{ctrl: ctrl}
	mock.recorder = &MockOrgClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockOrgClient) EXPECT() *MockOrgClientMockRecorder {
	return m.recorder
}

// CreateOrg mocks base method
func (m *MockOrgClient) CreateOrg(arg0 context.Context, arg1 *organization.CreateOrgRequest) (*user_service.OrgInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrg", arg0, arg1)
	ret0, _ := ret[0].(*user_service.OrgInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrg indicates an expected call of CreateOrg
func (mr *MockOrgClientMockRecorder) CreateOrg(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrg", reflect.TypeOf((*MockOrgClient)(nil).CreateOrg), arg0, arg1)
}

// DisableOrg mocks base method
func (m *MockOrgClient) DisableOrg(arg0 context.Context, arg1 *organization.DisableOrgRequest) (*types.Empty, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DisableOrg", arg0, arg1)
	ret0, _ := ret[0].(*types.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DisableOrg indicates an expected call of DisableOrg
func (mr *MockOrgClientMockRecorder) DisableOrg(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisableOrg", reflect.TypeOf((*MockOrgClient)(nil).DisableOrg), arg0, arg1)
}

// EnableOrg mocks base method
func (m *MockOrgClient) EnableOrg(arg0 context.Context, arg1 *organization.EnableOrgRequest) (*types.Empty, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnableOrg", arg0, arg1)
	ret0, _ := ret[0].(*types.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnableOrg indicates an expected call of EnableOrg
func (mr *MockOrgClientMockRecorder) EnableOrg(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnableOrg", reflect.TypeOf((*MockOrgClient)(nil).EnableOrg), arg0, arg1)
}

// GetCurrentOrg mocks base method
func (m *MockOrgClient) GetCurrentOrg(arg0 context.Context, arg1 *types.Empty) (*user_service.OrgInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentOrg", arg0, arg1)
	ret0, _ := ret[0].(*user_service.OrgInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentOrg indicates an expected call of GetCurrentOrg
func (mr *MockOrgClientMockRecorder) GetCurrentOrg(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentOrg", reflect.TypeOf((*MockOrgClient)(nil).GetCurrentOrg), arg0, arg1)
}

// GetOrgInfo mocks base method
func (m *MockOrgClient) GetOrgInfo(arg0 context.Context, arg1 *organization.GetOrgInfoRequest) (*user_service.OrgInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrgInfo", arg0, arg1)
	ret0, _ := ret[0].(*user_service.OrgInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrgInfo indicates an expected call of GetOrgInfo
func (mr *MockOrgClientMockRecorder) GetOrgInfo(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrgInfo", reflect.TypeOf((*MockOrgClient)(nil).GetOrgInfo), arg0, arg1)
}

// ListOrg mocks base method
func (m *MockOrgClient) ListOrg(arg0 context.Context, arg1 *types.Empty) (*organization.ListOrgResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOrg", arg0, arg1)
	ret0, _ := ret[0].(*organization.ListOrgResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOrg indicates an expected call of ListOrg
func (mr *MockOrgClientMockRecorder) ListOrg(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOrg", reflect.TypeOf((*MockOrgClient)(nil).ListOrg), arg0, arg1)
}

// SetOrgExpiredDate mocks base method
func (m *MockOrgClient) SetOrgExpiredDate(arg0 context.Context, arg1 *organization.SetOrgExpiredDateRequest) (*types.Empty, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetOrgExpiredDate", arg0, arg1)
	ret0, _ := ret[0].(*types.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetOrgExpiredDate indicates an expected call of SetOrgExpiredDate
func (mr *MockOrgClientMockRecorder) SetOrgExpiredDate(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetOrgExpiredDate", reflect.TypeOf((*MockOrgClient)(nil).SetOrgExpiredDate), arg0, arg1)
}

// SetOrgNamespaces mocks base method
func (m *MockOrgClient) SetOrgNamespaces(arg0 context.Context, arg1 *organization.SetOrgNamespacesRequest) (*types.Empty, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetOrgNamespaces", arg0, arg1)
	ret0, _ := ret[0].(*types.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetOrgNamespaces indicates an expected call of SetOrgNamespaces
func (mr *MockOrgClientMockRecorder) SetOrgNamespaces(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetOrgNamespaces", reflect.TypeOf((*MockOrgClient)(nil).SetOrgNamespaces), arg0, arg1)
}
