// Code generated by MockGen. DO NOT EDIT.
// Source: go.easyops.local/redis-helper/v8/lock (interfaces: Lock)

// Package redis is a generated GoMock package.
package redis

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockRedisLock is a mock of Lock interface.
type MockRedisLock struct {
	ctrl     *gomock.Controller
	recorder *MockRedisLockMockRecorder
}

// MockRedisLockMockRecorder is the mock recorder for MockRedisLock.
type MockRedisLockMockRecorder struct {
	mock *MockRedisLock
}

// NewMockRedisLock creates a new mock instance.
func NewMockRedisLock(ctrl *gomock.Controller) *MockRedisLock {
	mock := &MockRedisLock{ctrl: ctrl}
	mock.recorder = &MockRedisLockMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRedisLock) EXPECT() *MockRedisLockMockRecorder {
	return m.recorder
}

// Extend mocks base method.
func (m *MockRedisLock) Extend(arg0 context.Context, arg1 time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Extend", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Extend indicates an expected call of Extend.
func (mr *MockRedisLockMockRecorder) Extend(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Extend", reflect.TypeOf((*MockRedisLock)(nil).Extend), arg0, arg1)
}

// Lock mocks base method.
func (m *MockRedisLock) Lock() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Lock")
	ret0, _ := ret[0].(error)
	return ret0
}

// Lock indicates an expected call of Lock.
func (mr *MockRedisLockMockRecorder) Lock() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Lock", reflect.TypeOf((*MockRedisLock)(nil).Lock))
}

// LockContext mocks base method.
func (m *MockRedisLock) LockContext(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LockContext", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// LockContext indicates an expected call of LockContext.
func (mr *MockRedisLockMockRecorder) LockContext(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockContext", reflect.TypeOf((*MockRedisLock)(nil).LockContext), arg0)
}

// Unlock mocks base method.
func (m *MockRedisLock) Unlock() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unlock")
	ret0, _ := ret[0].(error)
	return ret0
}

// Unlock indicates an expected call of Unlock.
func (mr *MockRedisLockMockRecorder) Unlock() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unlock", reflect.TypeOf((*MockRedisLock)(nil).Unlock))
}

// UnlockContext mocks base method.
func (m *MockRedisLock) UnlockContext(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnlockContext", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnlockContext indicates an expected call of UnlockContext.
func (mr *MockRedisLockMockRecorder) UnlockContext(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnlockContext", reflect.TypeOf((*MockRedisLock)(nil).UnlockContext), arg0)
}
