// Code generated by MockGen. DO NOT EDIT.
// Source: go.easyops.local/contracts/protorepo-collector_center/collection_config (interfaces: Client)

// Package collector_center is a generated GoMock package.
package collector_center

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	collection_config "go.easyops.local/contracts/protorepo-collector_center/collection_config"
)

// MockcollectionClient is a mock of Client interface
type MockcollectionClient struct {
	ctrl     *gomock.Controller
	recorder *MockcollectionClientMockRecorder
}

// MockcollectionClientMockRecorder is the mock recorder for MockcollectionClient
type MockcollectionClientMockRecorder struct {
	mock *MockcollectionClient
}

// NewMockcollectionClient creates a new mock instance
func NewMockcollectionClient(ctrl *gomock.Controller) *MockcollectionClient {
	mock := &MockcollectionClient{ctrl: ctrl}
	mock.recorder = &MockcollectionClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockcollectionClient) EXPECT() *MockcollectionClientMockRecorder {
	return m.recorder
}

// CreateCollectionConfig mocks base method
func (m *MockcollectionClient) CreateCollectionConfig(arg0 context.Context, arg1 *collection_config.CreateCollectionConfigRequest) (*collection_config.CreateCollectionConfigResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCollectionConfig", arg0, arg1)
	ret0, _ := ret[0].(*collection_config.CreateCollectionConfigResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCollectionConfig indicates an expected call of CreateCollectionConfig
func (mr *MockcollectionClientMockRecorder) CreateCollectionConfig(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCollectionConfig", reflect.TypeOf((*MockcollectionClient)(nil).CreateCollectionConfig), arg0, arg1)
}

// DebugCollectionConfig mocks base method
func (m *MockcollectionClient) DebugCollectionConfig(arg0 context.Context, arg1 *collection_config.DebugCollectionConfigRequest) (*collection_config.DebugCollectionConfigResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DebugCollectionConfig", arg0, arg1)
	ret0, _ := ret[0].(*collection_config.DebugCollectionConfigResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DebugCollectionConfig indicates an expected call of DebugCollectionConfig
func (mr *MockcollectionClientMockRecorder) DebugCollectionConfig(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DebugCollectionConfig", reflect.TypeOf((*MockcollectionClient)(nil).DebugCollectionConfig), arg0, arg1)
}

// DebugCollectionConfigCallback mocks base method
func (m *MockcollectionClient) DebugCollectionConfigCallback(arg0 context.Context, arg1 *collection_config.DebugCollectionConfigCallbackRequest) (*collection_config.DebugCollectionConfigCallbackResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DebugCollectionConfigCallback", arg0, arg1)
	ret0, _ := ret[0].(*collection_config.DebugCollectionConfigCallbackResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DebugCollectionConfigCallback indicates an expected call of DebugCollectionConfigCallback
func (mr *MockcollectionClientMockRecorder) DebugCollectionConfigCallback(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DebugCollectionConfigCallback", reflect.TypeOf((*MockcollectionClient)(nil).DebugCollectionConfigCallback), arg0, arg1)
}

// DeleteCollectionConfig mocks base method
func (m *MockcollectionClient) DeleteCollectionConfig(arg0 context.Context, arg1 *collection_config.DeleteCollectionConfigRequest) (*collection_config.DeleteCollectionConfigResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCollectionConfig", arg0, arg1)
	ret0, _ := ret[0].(*collection_config.DeleteCollectionConfigResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteCollectionConfig indicates an expected call of DeleteCollectionConfig
func (mr *MockcollectionClientMockRecorder) DeleteCollectionConfig(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCollectionConfig", reflect.TypeOf((*MockcollectionClient)(nil).DeleteCollectionConfig), arg0, arg1)
}

// DetailCollectionConfig mocks base method
func (m *MockcollectionClient) DetailCollectionConfig(arg0 context.Context, arg1 *collection_config.DetailCollectionConfigRequest) (*collection_config.DetailCollectionConfigResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DetailCollectionConfig", arg0, arg1)
	ret0, _ := ret[0].(*collection_config.DetailCollectionConfigResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DetailCollectionConfig indicates an expected call of DetailCollectionConfig
func (mr *MockcollectionClientMockRecorder) DetailCollectionConfig(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DetailCollectionConfig", reflect.TypeOf((*MockcollectionClient)(nil).DetailCollectionConfig), arg0, arg1)
}

// DetailCollectionConfigDebug mocks base method
func (m *MockcollectionClient) DetailCollectionConfigDebug(arg0 context.Context, arg1 *collection_config.DetailCollectionConfigDebugRequest) (*collection_config.DetailCollectionConfigDebugResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DetailCollectionConfigDebug", arg0, arg1)
	ret0, _ := ret[0].(*collection_config.DetailCollectionConfigDebugResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DetailCollectionConfigDebug indicates an expected call of DetailCollectionConfigDebug
func (mr *MockcollectionClientMockRecorder) DetailCollectionConfigDebug(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DetailCollectionConfigDebug", reflect.TypeOf((*MockcollectionClient)(nil).DetailCollectionConfigDebug), arg0, arg1)
}

// DisableCollectionConfig mocks base method
func (m *MockcollectionClient) DisableCollectionConfig(arg0 context.Context, arg1 *collection_config.DisableCollectionConfigRequest) (*collection_config.DisableCollectionConfigResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DisableCollectionConfig", arg0, arg1)
	ret0, _ := ret[0].(*collection_config.DisableCollectionConfigResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DisableCollectionConfig indicates an expected call of DisableCollectionConfig
func (mr *MockcollectionClientMockRecorder) DisableCollectionConfig(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisableCollectionConfig", reflect.TypeOf((*MockcollectionClient)(nil).DisableCollectionConfig), arg0, arg1)
}

// ListCollectionConfig mocks base method
func (m *MockcollectionClient) ListCollectionConfig(arg0 context.Context, arg1 *collection_config.ListCollectionConfigRequest) (*collection_config.ListCollectionConfigResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCollectionConfig", arg0, arg1)
	ret0, _ := ret[0].(*collection_config.ListCollectionConfigResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCollectionConfig indicates an expected call of ListCollectionConfig
func (mr *MockcollectionClientMockRecorder) ListCollectionConfig(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCollectionConfig", reflect.TypeOf((*MockcollectionClient)(nil).ListCollectionConfig), arg0, arg1)
}

// ListCollectionConfigJobs mocks base method
func (m *MockcollectionClient) ListCollectionConfigJobs(arg0 context.Context, arg1 *collection_config.ListCollectionConfigJobsRequest) (*collection_config.ListCollectionConfigJobsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCollectionConfigJobs", arg0, arg1)
	ret0, _ := ret[0].(*collection_config.ListCollectionConfigJobsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCollectionConfigJobs indicates an expected call of ListCollectionConfigJobs
func (mr *MockcollectionClientMockRecorder) ListCollectionConfigJobs(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCollectionConfigJobs", reflect.TypeOf((*MockcollectionClient)(nil).ListCollectionConfigJobs), arg0, arg1)
}

// MaintainCollectionConfigJob mocks base method
func (m *MockcollectionClient) MaintainCollectionConfigJob(arg0 context.Context, arg1 *collection_config.MaintainCollectionConfigJobRequest) (*collection_config.MaintainCollectionConfigJobResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MaintainCollectionConfigJob", arg0, arg1)
	ret0, _ := ret[0].(*collection_config.MaintainCollectionConfigJobResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MaintainCollectionConfigJob indicates an expected call of MaintainCollectionConfigJob
func (mr *MockcollectionClientMockRecorder) MaintainCollectionConfigJob(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MaintainCollectionConfigJob", reflect.TypeOf((*MockcollectionClient)(nil).MaintainCollectionConfigJob), arg0, arg1)
}

// UpdateCollectionConfig mocks base method
func (m *MockcollectionClient) UpdateCollectionConfig(arg0 context.Context, arg1 *collection_config.UpdateCollectionConfigRequest) (*collection_config.UpdateCollectionConfigResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCollectionConfig", arg0, arg1)
	ret0, _ := ret[0].(*collection_config.UpdateCollectionConfigResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCollectionConfig indicates an expected call of UpdateCollectionConfig
func (mr *MockcollectionClientMockRecorder) UpdateCollectionConfig(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCollectionConfig", reflect.TypeOf((*MockcollectionClient)(nil).UpdateCollectionConfig), arg0, arg1)
}
