// Code generated by giraffe-go. DO NOT EDIT.
package fill_instance

import (
	"github.com/gin-gonic/gin"
	types "github.com/gogo/protobuf/types"

	message "go.easyops.local/contracts/protorepo-fintech_data/fill_instance"
	"go.easyops.local/fintech_data/fill_instance/validators"
	"go.easyops.local/fintech_data/internal/apierrors"
	"go.easyops.local/kit/gerr"
	kitweb "go.easyops.local/kit/web"
	"go.easyops.local/slog"
	logctx "go.easyops.local/slog/context"
)

var _ kitweb.JSONPb
var _ = apierrors.ErrInvalidArgument
var _ = types.Struct{}
var _ = validators.EmptyTree

type FillInstanceController struct {
	logger  slog.Logger
	service FillInstanceService
}

func NewFillInstanceController(logger slog.Logger, service FillInstanceService) *FillInstanceController {
	return &FillInstanceController{
		logger:  logger,
		service: service,
	}
}

func (s *FillInstanceController) InstanceCallback(ctx *gin.Context) {
	logger := logctx.MustGetLogger(ctx.Request.Context())
	var _ = logger
	var err error

	request, err := validators.ValidateInstanceCallback(ctx)
	if err != nil {
		apiError := gerr.ToApiError(err)
		ctx.JSON(apiError.Status(), apiError.Data())
		return
	}

	data, err := s.service.InstanceCallback(ctx.Request.Context(), request)
	if err != nil {
		apiError := gerr.ToApiError(err)
		ctx.JSON(apiError.Status(), apiError.Data())
		return
	} else {

		ctx.Render(200, kitweb.JSONPb{
			Data: &message.InstanceCallbackResponseWrapper{
				Data: data,
			},
			UseCustomMarshaler: true,
			UseGogo:            true,
		})
		return

	}
}
