// Code generated by giraffe-go. DO NOT EDIT.
package fill_instance

import "github.com/gin-gonic/gin"

func (s *FillInstanceController) Register(engine *gin.Engine) {
	engine.POST("/api/fill/instance/callback", s.InstanceCallback)
}
