// Code generated by giraffe-go. DO NOT EDIT.
package fill_instance

import (
	message "go.easyops.local/contracts/protorepo-fintech_data/fill_instance"

	"context"
	"io"
	"mime/multipart"

	"github.com/gin-gonic/gin/render"
	types "github.com/gogo/protobuf/types"
)

var _ = render.WriteJSON
var _ = multipart.NewReader
var _ = io.Copy
var _ = types.Struct{}
var _ = message.NewClient

type FillInstanceService interface {
	InstanceCallback(ctx context.Context, request *message.InstanceCallbackRequest) (*types.Empty, error)
}
