// Code generated by MockGen. DO NOT EDIT.
// Source: go.easyops.local/contracts/protorepo-cmdb/cmdb_object (interfaces: Client)

// Package cmdb is a generated GoMock package.
package cmdb

import (
	context "context"
	reflect "reflect"

	types "github.com/gogo/protobuf/types"
	gomock "github.com/golang/mock/gomock"
	cmdb_object "go.easyops.local/contracts/protorepo-cmdb/cmdb_object"
	cmdb "go.easyops.local/contracts/protorepo-models/easyops/model/cmdb"
)

// MockObjectClient is a mock of Client interface.
type MockObjectClient struct {
	ctrl     *gomock.Controller
	recorder *MockObjectClientMockRecorder
}

// MockObjectClientMockRecorder is the mock recorder for MockObjectClient.
type MockObjectClientMockRecorder struct {
	mock *MockObjectClient
}

// NewMockObjectClient creates a new mock instance.
func NewMockObjectClient(ctrl *gomock.Controller) *MockObjectClient {
	mock := &MockObjectClient{ctrl: ctrl}
	mock.recorder = &MockObjectClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockObjectClient) EXPECT() *MockObjectClientMockRecorder {
	return m.recorder
}

// AlertNotifyDenied mocks base method.
func (m *MockObjectClient) AlertNotifyDenied(arg0 context.Context, arg1 *cmdb_object.AlertNotifyDeniedRequest) (*types.Empty, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AlertNotifyDenied", arg0, arg1)
	ret0, _ := ret[0].(*types.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AlertNotifyDenied indicates an expected call of AlertNotifyDenied.
func (mr *MockObjectClientMockRecorder) AlertNotifyDenied(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AlertNotifyDenied", reflect.TypeOf((*MockObjectClient)(nil).AlertNotifyDenied), arg0, arg1)
}

// AlertWordIndex mocks base method.
func (m *MockObjectClient) AlertWordIndex(arg0 context.Context, arg1 *cmdb_object.AlertWordIndexRequest) (*types.Empty, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AlertWordIndex", arg0, arg1)
	ret0, _ := ret[0].(*types.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AlertWordIndex indicates an expected call of AlertWordIndex.
func (mr *MockObjectClientMockRecorder) AlertWordIndex(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AlertWordIndex", reflect.TypeOf((*MockObjectClient)(nil).AlertWordIndex), arg0, arg1)
}

// BatchListRelationQueryStrategyV2Request mocks base method.
func (m *MockObjectClient) BatchListRelationQueryStrategyV2Request(arg0 context.Context, arg1 *cmdb_object.BatchListRelationQueryStrategyV2RequestRequest) (*cmdb_object.BatchListRelationQueryStrategyV2RequestResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchListRelationQueryStrategyV2Request", arg0, arg1)
	ret0, _ := ret[0].(*cmdb_object.BatchListRelationQueryStrategyV2RequestResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchListRelationQueryStrategyV2Request indicates an expected call of BatchListRelationQueryStrategyV2Request.
func (mr *MockObjectClientMockRecorder) BatchListRelationQueryStrategyV2Request(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchListRelationQueryStrategyV2Request", reflect.TypeOf((*MockObjectClient)(nil).BatchListRelationQueryStrategyV2Request), arg0, arg1)
}

// BatchUpdate mocks base method.
func (m *MockObjectClient) BatchUpdate(arg0 context.Context, arg1 *cmdb_object.BatchUpdateRequest) (*cmdb_object.BatchUpdateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchUpdate", arg0, arg1)
	ret0, _ := ret[0].(*cmdb_object.BatchUpdateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchUpdate indicates an expected call of BatchUpdate.
func (mr *MockObjectClientMockRecorder) BatchUpdate(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchUpdate", reflect.TypeOf((*MockObjectClient)(nil).BatchUpdate), arg0, arg1)
}

// Create mocks base method.
func (m *MockObjectClient) Create(arg0 context.Context, arg1 *cmdb_object.CreateRequest) (*cmdb.CmdbObject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(*cmdb.CmdbObject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockObjectClientMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockObjectClient)(nil).Create), arg0, arg1)
}

// CreateRelationQueryStrategyV2 mocks base method.
func (m *MockObjectClient) CreateRelationQueryStrategyV2(arg0 context.Context, arg1 *cmdb_object.CreateRelationQueryStrategyV2Request) (*cmdb.RelationQueryStrategyV2, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRelationQueryStrategyV2", arg0, arg1)
	ret0, _ := ret[0].(*cmdb.RelationQueryStrategyV2)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRelationQueryStrategyV2 indicates an expected call of CreateRelationQueryStrategyV2.
func (mr *MockObjectClientMockRecorder) CreateRelationQueryStrategyV2(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRelationQueryStrategyV2", reflect.TypeOf((*MockObjectClient)(nil).CreateRelationQueryStrategyV2), arg0, arg1)
}

// DeleteObject mocks base method.
func (m *MockObjectClient) DeleteObject(arg0 context.Context, arg1 *cmdb_object.DeleteObjectRequest) (*cmdb.CmdbObject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteObject", arg0, arg1)
	ret0, _ := ret[0].(*cmdb.CmdbObject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteObject indicates an expected call of DeleteObject.
func (mr *MockObjectClientMockRecorder) DeleteObject(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteObject", reflect.TypeOf((*MockObjectClient)(nil).DeleteObject), arg0, arg1)
}

// DeleteProperty mocks base method.
func (m *MockObjectClient) DeleteProperty(arg0 context.Context, arg1 *cmdb_object.DeletePropertyRequest) (*cmdb.ObjectAttr, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProperty", arg0, arg1)
	ret0, _ := ret[0].(*cmdb.ObjectAttr)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteProperty indicates an expected call of DeleteProperty.
func (mr *MockObjectClientMockRecorder) DeleteProperty(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProperty", reflect.TypeOf((*MockObjectClient)(nil).DeleteProperty), arg0, arg1)
}

// DeleteRelationQueryStrategyV2 mocks base method.
func (m *MockObjectClient) DeleteRelationQueryStrategyV2(arg0 context.Context, arg1 *cmdb_object.DeleteRelationQueryStrategyV2Request) (*types.Empty, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRelationQueryStrategyV2", arg0, arg1)
	ret0, _ := ret[0].(*types.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteRelationQueryStrategyV2 indicates an expected call of DeleteRelationQueryStrategyV2.
func (mr *MockObjectClientMockRecorder) DeleteRelationQueryStrategyV2(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRelationQueryStrategyV2", reflect.TypeOf((*MockObjectClient)(nil).DeleteRelationQueryStrategyV2), arg0, arg1)
}

// ExportObject mocks base method.
func (m *MockObjectClient) ExportObject(arg0 context.Context, arg1 *cmdb_object.ExportObjectRequest) (*cmdb_object.ExportObjectResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExportObject", arg0, arg1)
	ret0, _ := ret[0].(*cmdb_object.ExportObjectResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExportObject indicates an expected call of ExportObject.
func (mr *MockObjectClientMockRecorder) ExportObject(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExportObject", reflect.TypeOf((*MockObjectClient)(nil).ExportObject), arg0, arg1)
}

// ExportObjectV2 mocks base method.
func (m *MockObjectClient) ExportObjectV2(arg0 context.Context, arg1 *cmdb_object.ExportObjectV2Request) (*cmdb_object.ExportObjectV2Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExportObjectV2", arg0, arg1)
	ret0, _ := ret[0].(*cmdb_object.ExportObjectV2Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExportObjectV2 indicates an expected call of ExportObjectV2.
func (mr *MockObjectClientMockRecorder) ExportObjectV2(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExportObjectV2", reflect.TypeOf((*MockObjectClient)(nil).ExportObjectV2), arg0, arg1)
}

// GetDetail mocks base method.
func (m *MockObjectClient) GetDetail(arg0 context.Context, arg1 *cmdb_object.GetDetailRequest) (*cmdb.CmdbObject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDetail", arg0, arg1)
	ret0, _ := ret[0].(*cmdb.CmdbObject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDetail indicates an expected call of GetDetail.
func (mr *MockObjectClientMockRecorder) GetDetail(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDetail", reflect.TypeOf((*MockObjectClient)(nil).GetDetail), arg0, arg1)
}

// GetIdMapName mocks base method.
func (m *MockObjectClient) GetIdMapName(arg0 context.Context, arg1 *cmdb_object.GetIdMapNameRequest) (*types.Struct, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIdMapName", arg0, arg1)
	ret0, _ := ret[0].(*types.Struct)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIdMapName indicates an expected call of GetIdMapName.
func (mr *MockObjectClientMockRecorder) GetIdMapName(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIdMapName", reflect.TypeOf((*MockObjectClient)(nil).GetIdMapName), arg0, arg1)
}

// GetObjectAll mocks base method.
func (m *MockObjectClient) GetObjectAll(arg0 context.Context, arg1 *cmdb_object.GetObjectAllRequest) (*cmdb_object.GetObjectAllResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObjectAll", arg0, arg1)
	ret0, _ := ret[0].(*cmdb_object.GetObjectAllResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObjectAll indicates an expected call of GetObjectAll.
func (mr *MockObjectClientMockRecorder) GetObjectAll(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObjectAll", reflect.TypeOf((*MockObjectClient)(nil).GetObjectAll), arg0, arg1)
}

// GetObjectAuthorizers mocks base method.
func (m *MockObjectClient) GetObjectAuthorizers(arg0 context.Context, arg1 *cmdb_object.GetObjectAuthorizersRequest) (*cmdb_object.GetObjectAuthorizersResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObjectAuthorizers", arg0, arg1)
	ret0, _ := ret[0].(*cmdb_object.GetObjectAuthorizersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObjectAuthorizers indicates an expected call of GetObjectAuthorizers.
func (mr *MockObjectClientMockRecorder) GetObjectAuthorizers(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObjectAuthorizers", reflect.TypeOf((*MockObjectClient)(nil).GetObjectAuthorizers), arg0, arg1)
}

// GetObjectBasicAll mocks base method.
func (m *MockObjectClient) GetObjectBasicAll(arg0 context.Context, arg1 *cmdb.ListObjectRequest) (*cmdb_object.GetObjectBasicAllResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObjectBasicAll", arg0, arg1)
	ret0, _ := ret[0].(*cmdb_object.GetObjectBasicAllResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObjectBasicAll indicates an expected call of GetObjectBasicAll.
func (mr *MockObjectClientMockRecorder) GetObjectBasicAll(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObjectBasicAll", reflect.TypeOf((*MockObjectClient)(nil).GetObjectBasicAll), arg0, arg1)
}

// GetObjectRef mocks base method.
func (m *MockObjectClient) GetObjectRef(arg0 context.Context, arg1 *cmdb_object.GetObjectRefRequest) (*cmdb_object.GetObjectRefResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObjectRef", arg0, arg1)
	ret0, _ := ret[0].(*cmdb_object.GetObjectRefResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObjectRef indicates an expected call of GetObjectRef.
func (mr *MockObjectClientMockRecorder) GetObjectRef(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObjectRef", reflect.TypeOf((*MockObjectClient)(nil).GetObjectRef), arg0, arg1)
}

// GetObjectRelationPath mocks base method.
func (m *MockObjectClient) GetObjectRelationPath(arg0 context.Context, arg1 *cmdb_object.GetObjectRelationPathRequest) (*cmdb_object.GetObjectRelationPathResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObjectRelationPath", arg0, arg1)
	ret0, _ := ret[0].(*cmdb_object.GetObjectRelationPathResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObjectRelationPath indicates an expected call of GetObjectRelationPath.
func (mr *MockObjectClientMockRecorder) GetObjectRelationPath(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObjectRelationPath", reflect.TypeOf((*MockObjectClient)(nil).GetObjectRelationPath), arg0, arg1)
}

// GetObjectRelationRelatedKey mocks base method.
func (m *MockObjectClient) GetObjectRelationRelatedKey(arg0 context.Context, arg1 *cmdb_object.GetObjectRelationRelatedKeyRequest) (*cmdb_object.GetObjectRelationRelatedKeyResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObjectRelationRelatedKey", arg0, arg1)
	ret0, _ := ret[0].(*cmdb_object.GetObjectRelationRelatedKeyResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObjectRelationRelatedKey indicates an expected call of GetObjectRelationRelatedKey.
func (mr *MockObjectClientMockRecorder) GetObjectRelationRelatedKey(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObjectRelationRelatedKey", reflect.TypeOf((*MockObjectClient)(nil).GetObjectRelationRelatedKey), arg0, arg1)
}

// GetProperty mocks base method.
func (m *MockObjectClient) GetProperty(arg0 context.Context, arg1 *cmdb_object.GetPropertyRequest) (*cmdb.ObjectAttr, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProperty", arg0, arg1)
	ret0, _ := ret[0].(*cmdb.ObjectAttr)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProperty indicates an expected call of GetProperty.
func (mr *MockObjectClientMockRecorder) GetProperty(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProperty", reflect.TypeOf((*MockObjectClient)(nil).GetProperty), arg0, arg1)
}

// GetRelationQueryStrategyV2 mocks base method.
func (m *MockObjectClient) GetRelationQueryStrategyV2(arg0 context.Context, arg1 *cmdb_object.GetRelationQueryStrategyV2Request) (*cmdb.RelationQueryStrategyV2, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRelationQueryStrategyV2", arg0, arg1)
	ret0, _ := ret[0].(*cmdb.RelationQueryStrategyV2)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRelationQueryStrategyV2 indicates an expected call of GetRelationQueryStrategyV2.
func (mr *MockObjectClientMockRecorder) GetRelationQueryStrategyV2(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRelationQueryStrategyV2", reflect.TypeOf((*MockObjectClient)(nil).GetRelationQueryStrategyV2), arg0, arg1)
}

// ImportCheck mocks base method.
func (m *MockObjectClient) ImportCheck(arg0 context.Context, arg1 *cmdb_object.ImportCheckRequest) (*cmdb_object.ImportCheckResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImportCheck", arg0, arg1)
	ret0, _ := ret[0].(*cmdb_object.ImportCheckResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ImportCheck indicates an expected call of ImportCheck.
func (mr *MockObjectClientMockRecorder) ImportCheck(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImportCheck", reflect.TypeOf((*MockObjectClient)(nil).ImportCheck), arg0, arg1)
}

// ImportCheckV2 mocks base method.
func (m *MockObjectClient) ImportCheckV2(arg0 context.Context, arg1 *cmdb_object.ImportCheckV2Request) (*cmdb_object.ImportCheckV2Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImportCheckV2", arg0, arg1)
	ret0, _ := ret[0].(*cmdb_object.ImportCheckV2Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ImportCheckV2 indicates an expected call of ImportCheckV2.
func (mr *MockObjectClientMockRecorder) ImportCheckV2(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImportCheckV2", reflect.TypeOf((*MockObjectClient)(nil).ImportCheckV2), arg0, arg1)
}

// ImportObject mocks base method.
func (m *MockObjectClient) ImportObject(arg0 context.Context, arg1 *cmdb_object.ImportObjectRequest) (*cmdb_object.ImportObjectResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImportObject", arg0, arg1)
	ret0, _ := ret[0].(*cmdb_object.ImportObjectResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ImportObject indicates an expected call of ImportObject.
func (mr *MockObjectClientMockRecorder) ImportObject(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImportObject", reflect.TypeOf((*MockObjectClient)(nil).ImportObject), arg0, arg1)
}

// ImportV2 mocks base method.
func (m *MockObjectClient) ImportV2(arg0 context.Context, arg1 *cmdb_object.ImportV2Request) (*cmdb_object.ImportV2Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImportV2", arg0, arg1)
	ret0, _ := ret[0].(*cmdb_object.ImportV2Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ImportV2 indicates an expected call of ImportV2.
func (mr *MockObjectClientMockRecorder) ImportV2(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImportV2", reflect.TypeOf((*MockObjectClient)(nil).ImportV2), arg0, arg1)
}

// List mocks base method.
func (m *MockObjectClient) List(arg0 context.Context, arg1 *cmdb_object.ListRequest) (*cmdb_object.ListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].(*cmdb_object.ListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockObjectClientMockRecorder) List(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockObjectClient)(nil).List), arg0, arg1)
}

// ListChildObject mocks base method.
func (m *MockObjectClient) ListChildObject(arg0 context.Context, arg1 *cmdb_object.ListChildObjectRequest) (*cmdb_object.ListChildObjectResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListChildObject", arg0, arg1)
	ret0, _ := ret[0].(*cmdb_object.ListChildObjectResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListChildObject indicates an expected call of ListChildObject.
func (mr *MockObjectClientMockRecorder) ListChildObject(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListChildObject", reflect.TypeOf((*MockObjectClient)(nil).ListChildObject), arg0, arg1)
}

// ListObjectBasic mocks base method.
func (m *MockObjectClient) ListObjectBasic(arg0 context.Context, arg1 *cmdb_object.ListObjectBasicRequest) (*cmdb_object.ListObjectBasicResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListObjectBasic", arg0, arg1)
	ret0, _ := ret[0].(*cmdb_object.ListObjectBasicResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListObjectBasic indicates an expected call of ListObjectBasic.
func (mr *MockObjectClientMockRecorder) ListObjectBasic(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListObjectBasic", reflect.TypeOf((*MockObjectClient)(nil).ListObjectBasic), arg0, arg1)
}

// ListObjectCategory mocks base method.
func (m *MockObjectClient) ListObjectCategory(arg0 context.Context, arg1 *cmdb_object.ListObjectCategoryRequest) (*cmdb_object.ListObjectCategoryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListObjectCategory", arg0, arg1)
	ret0, _ := ret[0].(*cmdb_object.ListObjectCategoryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListObjectCategory indicates an expected call of ListObjectCategory.
func (mr *MockObjectClientMockRecorder) ListObjectCategory(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListObjectCategory", reflect.TypeOf((*MockObjectClient)(nil).ListObjectCategory), arg0, arg1)
}

// ListObjectCategoryV2 mocks base method.
func (m *MockObjectClient) ListObjectCategoryV2(arg0 context.Context, arg1 *cmdb_object.ListObjectCategoryV2Request) (*cmdb_object.ListObjectCategoryV2Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListObjectCategoryV2", arg0, arg1)
	ret0, _ := ret[0].(*cmdb_object.ListObjectCategoryV2Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListObjectCategoryV2 indicates an expected call of ListObjectCategoryV2.
func (mr *MockObjectClientMockRecorder) ListObjectCategoryV2(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListObjectCategoryV2", reflect.TypeOf((*MockObjectClient)(nil).ListObjectCategoryV2), arg0, arg1)
}

// ListObjectFields mocks base method.
func (m *MockObjectClient) ListObjectFields(arg0 context.Context, arg1 *cmdb_object.ListObjectFieldsRequest) (*cmdb_object.ListObjectFieldsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListObjectFields", arg0, arg1)
	ret0, _ := ret[0].(*cmdb_object.ListObjectFieldsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListObjectFields indicates an expected call of ListObjectFields.
func (mr *MockObjectClientMockRecorder) ListObjectFields(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListObjectFields", reflect.TypeOf((*MockObjectClient)(nil).ListObjectFields), arg0, arg1)
}

// ListRelationQueryStrategyV2Request mocks base method.
func (m *MockObjectClient) ListRelationQueryStrategyV2Request(arg0 context.Context, arg1 *cmdb_object.ListRelationQueryStrategyV2RequestRequest) (*cmdb_object.ListRelationQueryStrategyV2RequestResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRelationQueryStrategyV2Request", arg0, arg1)
	ret0, _ := ret[0].(*cmdb_object.ListRelationQueryStrategyV2RequestResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRelationQueryStrategyV2Request indicates an expected call of ListRelationQueryStrategyV2Request.
func (mr *MockObjectClientMockRecorder) ListRelationQueryStrategyV2Request(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRelationQueryStrategyV2Request", reflect.TypeOf((*MockObjectClient)(nil).ListRelationQueryStrategyV2Request), arg0, arg1)
}

// ObjectConflictCheck mocks base method.
func (m *MockObjectClient) ObjectConflictCheck(arg0 context.Context, arg1 *cmdb_object.ObjectConflictCheckRequest) (*cmdb_object.ObjectConflictCheckResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ObjectConflictCheck", arg0, arg1)
	ret0, _ := ret[0].(*cmdb_object.ObjectConflictCheckResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ObjectConflictCheck indicates an expected call of ObjectConflictCheck.
func (mr *MockObjectClientMockRecorder) ObjectConflictCheck(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ObjectConflictCheck", reflect.TypeOf((*MockObjectClient)(nil).ObjectConflictCheck), arg0, arg1)
}

// ObjectSnapshot mocks base method.
func (m *MockObjectClient) ObjectSnapshot(arg0 context.Context, arg1 *cmdb_object.ObjectSnapshotRequest) (*cmdb_object.ObjectSnapshotResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ObjectSnapshot", arg0, arg1)
	ret0, _ := ret[0].(*cmdb_object.ObjectSnapshotResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ObjectSnapshot indicates an expected call of ObjectSnapshot.
func (mr *MockObjectClientMockRecorder) ObjectSnapshot(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ObjectSnapshot", reflect.TypeOf((*MockObjectClient)(nil).ObjectSnapshot), arg0, arg1)
}

// Update mocks base method.
func (m *MockObjectClient) Update(arg0 context.Context, arg1 *cmdb_object.UpdateRequest) (*cmdb.CmdbObject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(*cmdb.CmdbObject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockObjectClientMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockObjectClient)(nil).Update), arg0, arg1)
}

// UpdateAttributeCategory mocks base method.
func (m *MockObjectClient) UpdateAttributeCategory(arg0 context.Context, arg1 *cmdb_object.UpdateAttributeCategoryRequest) (*types.Empty, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAttributeCategory", arg0, arg1)
	ret0, _ := ret[0].(*types.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAttributeCategory indicates an expected call of UpdateAttributeCategory.
func (mr *MockObjectClientMockRecorder) UpdateAttributeCategory(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAttributeCategory", reflect.TypeOf((*MockObjectClient)(nil).UpdateAttributeCategory), arg0, arg1)
}

// UpdateProperty mocks base method.
func (m *MockObjectClient) UpdateProperty(arg0 context.Context, arg1 *cmdb_object.UpdatePropertyRequest) (*cmdb.ObjectAttr, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProperty", arg0, arg1)
	ret0, _ := ret[0].(*cmdb.ObjectAttr)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateProperty indicates an expected call of UpdateProperty.
func (mr *MockObjectClientMockRecorder) UpdateProperty(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProperty", reflect.TypeOf((*MockObjectClient)(nil).UpdateProperty), arg0, arg1)
}

// UpdateRelationQueryStrategyV2 mocks base method.
func (m *MockObjectClient) UpdateRelationQueryStrategyV2(arg0 context.Context, arg1 *cmdb_object.UpdateRelationQueryStrategyV2Request) (*cmdb.RelationQueryStrategyV2, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRelationQueryStrategyV2", arg0, arg1)
	ret0, _ := ret[0].(*cmdb.RelationQueryStrategyV2)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateRelationQueryStrategyV2 indicates an expected call of UpdateRelationQueryStrategyV2.
func (mr *MockObjectClientMockRecorder) UpdateRelationQueryStrategyV2(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRelationQueryStrategyV2", reflect.TypeOf((*MockObjectClient)(nil).UpdateRelationQueryStrategyV2), arg0, arg1)
}

// UpdateV2 mocks base method.
func (m *MockObjectClient) UpdateV2(arg0 context.Context, arg1 *cmdb_object.UpdateV2Request) (*cmdb.CmdbObject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateV2", arg0, arg1)
	ret0, _ := ret[0].(*cmdb.CmdbObject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateV2 indicates an expected call of UpdateV2.
func (mr *MockObjectClientMockRecorder) UpdateV2(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateV2", reflect.TypeOf((*MockObjectClient)(nil).UpdateV2), arg0, arg1)
}
