// Code generated by MockGen. DO NOT EDIT.
// Source: go.easyops.local/contracts/protorepo-cmdb/instance (interfaces: Client)

// Package cmdb is a generated GoMock package.
package cmdb

import (
	context "context"
	reflect "reflect"

	types "github.com/gogo/protobuf/types"
	gomock "github.com/golang/mock/gomock"
	instance "go.easyops.local/contracts/protorepo-cmdb/instance"
	cmdb "go.easyops.local/contracts/protorepo-models/easyops/model/cmdb"
)

// MockInstanceClient is a mock of Client interface.
type MockInstanceClient struct {
	ctrl     *gomock.Controller
	recorder *MockInstanceClientMockRecorder
}

// MockInstanceClientMockRecorder is the mock recorder for MockInstanceClient.
type MockInstanceClientMockRecorder struct {
	mock *MockInstanceClient
}

// NewMockInstanceClient creates a new mock instance.
func NewMockInstanceClient(ctrl *gomock.Controller) *MockInstanceClient {
	mock := &MockInstanceClient{ctrl: ctrl}
	mock.recorder = &MockInstanceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInstanceClient) EXPECT() *MockInstanceClientMockRecorder {
	return m.recorder
}

// AggregateCount mocks base method.
func (m *MockInstanceClient) AggregateCount(arg0 context.Context, arg1 *instance.AggregateCountRequest) (*instance.AggregateCountResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AggregateCount", arg0, arg1)
	ret0, _ := ret[0].(*instance.AggregateCountResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AggregateCount indicates an expected call of AggregateCount.
func (mr *MockInstanceClientMockRecorder) AggregateCount(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AggregateCount", reflect.TypeOf((*MockInstanceClient)(nil).AggregateCount), arg0, arg1)
}

// AggregateInstance mocks base method.
func (m *MockInstanceClient) AggregateInstance(arg0 context.Context, arg1 *instance.AggregateInstanceRequest) (*instance.AggregateInstanceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AggregateInstance", arg0, arg1)
	ret0, _ := ret[0].(*instance.AggregateInstanceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AggregateInstance indicates an expected call of AggregateInstance.
func (mr *MockInstanceClientMockRecorder) AggregateInstance(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AggregateInstance", reflect.TypeOf((*MockInstanceClient)(nil).AggregateInstance), arg0, arg1)
}

// AutoDiscovery mocks base method.
func (m *MockInstanceClient) AutoDiscovery(arg0 context.Context, arg1 *instance.AutoDiscoveryRequest) (*instance.AutoDiscoveryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AutoDiscovery", arg0, arg1)
	ret0, _ := ret[0].(*instance.AutoDiscoveryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AutoDiscovery indicates an expected call of AutoDiscovery.
func (mr *MockInstanceClientMockRecorder) AutoDiscovery(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AutoDiscovery", reflect.TypeOf((*MockInstanceClient)(nil).AutoDiscovery), arg0, arg1)
}

// BatchListInstanceQueryStrategy mocks base method.
func (m *MockInstanceClient) BatchListInstanceQueryStrategy(arg0 context.Context, arg1 *instance.BatchListInstanceQueryStrategyRequest) (*instance.BatchListInstanceQueryStrategyResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchListInstanceQueryStrategy", arg0, arg1)
	ret0, _ := ret[0].(*instance.BatchListInstanceQueryStrategyResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchListInstanceQueryStrategy indicates an expected call of BatchListInstanceQueryStrategy.
func (mr *MockInstanceClientMockRecorder) BatchListInstanceQueryStrategy(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchListInstanceQueryStrategy", reflect.TypeOf((*MockInstanceClient)(nil).BatchListInstanceQueryStrategy), arg0, arg1)
}

// BatchSearch mocks base method.
func (m *MockInstanceClient) BatchSearch(arg0 context.Context, arg1 *instance.BatchSearchRequest) (*instance.BatchSearchResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchSearch", arg0, arg1)
	ret0, _ := ret[0].(*instance.BatchSearchResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchSearch indicates an expected call of BatchSearch.
func (mr *MockInstanceClientMockRecorder) BatchSearch(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchSearch", reflect.TypeOf((*MockInstanceClient)(nil).BatchSearch), arg0, arg1)
}

// CountAll mocks base method.
func (m *MockInstanceClient) CountAll(arg0 context.Context, arg1 *instance.CountAllRequest) (*types.Struct, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountAll", arg0, arg1)
	ret0, _ := ret[0].(*types.Struct)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountAll indicates an expected call of CountAll.
func (mr *MockInstanceClientMockRecorder) CountAll(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountAll", reflect.TypeOf((*MockInstanceClient)(nil).CountAll), arg0, arg1)
}

// CreateInstance mocks base method.
func (m *MockInstanceClient) CreateInstance(arg0 context.Context, arg1 *instance.CreateInstanceRequest) (*types.Struct, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInstance", arg0, arg1)
	ret0, _ := ret[0].(*types.Struct)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateInstance indicates an expected call of CreateInstance.
func (mr *MockInstanceClientMockRecorder) CreateInstance(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInstance", reflect.TypeOf((*MockInstanceClient)(nil).CreateInstance), arg0, arg1)
}

// CreateInstanceQueryStrategy mocks base method.
func (m *MockInstanceClient) CreateInstanceQueryStrategy(arg0 context.Context, arg1 *instance.CreateInstanceQueryStrategyRequest) (*cmdb.InstanceQueryStrategy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInstanceQueryStrategy", arg0, arg1)
	ret0, _ := ret[0].(*cmdb.InstanceQueryStrategy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateInstanceQueryStrategy indicates an expected call of CreateInstanceQueryStrategy.
func (mr *MockInstanceClientMockRecorder) CreateInstanceQueryStrategy(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInstanceQueryStrategy", reflect.TypeOf((*MockInstanceClient)(nil).CreateInstanceQueryStrategy), arg0, arg1)
}

// DeleteInstance mocks base method.
func (m *MockInstanceClient) DeleteInstance(arg0 context.Context, arg1 *instance.DeleteInstanceRequest) (*types.Struct, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteInstance", arg0, arg1)
	ret0, _ := ret[0].(*types.Struct)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteInstance indicates an expected call of DeleteInstance.
func (mr *MockInstanceClientMockRecorder) DeleteInstance(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteInstance", reflect.TypeOf((*MockInstanceClient)(nil).DeleteInstance), arg0, arg1)
}

// DeleteInstanceBatch mocks base method.
func (m *MockInstanceClient) DeleteInstanceBatch(arg0 context.Context, arg1 *instance.DeleteInstanceBatchRequest) (*instance.DeleteInstanceBatchResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteInstanceBatch", arg0, arg1)
	ret0, _ := ret[0].(*instance.DeleteInstanceBatchResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteInstanceBatch indicates an expected call of DeleteInstanceBatch.
func (mr *MockInstanceClientMockRecorder) DeleteInstanceBatch(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteInstanceBatch", reflect.TypeOf((*MockInstanceClient)(nil).DeleteInstanceBatch), arg0, arg1)
}

// DeleteInstanceQueryStrategy mocks base method.
func (m *MockInstanceClient) DeleteInstanceQueryStrategy(arg0 context.Context, arg1 *instance.DeleteInstanceQueryStrategyRequest) (*cmdb.InstanceQueryStrategy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteInstanceQueryStrategy", arg0, arg1)
	ret0, _ := ret[0].(*cmdb.InstanceQueryStrategy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteInstanceQueryStrategy indicates an expected call of DeleteInstanceQueryStrategy.
func (mr *MockInstanceClientMockRecorder) DeleteInstanceQueryStrategy(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteInstanceQueryStrategy", reflect.TypeOf((*MockInstanceClient)(nil).DeleteInstanceQueryStrategy), arg0, arg1)
}

// FulltextSearch mocks base method.
func (m *MockInstanceClient) FulltextSearch(arg0 context.Context, arg1 *instance.FulltextSearchRequest) (*instance.FulltextSearchResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FulltextSearch", arg0, arg1)
	ret0, _ := ret[0].(*instance.FulltextSearchResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FulltextSearch indicates an expected call of FulltextSearch.
func (mr *MockInstanceClientMockRecorder) FulltextSearch(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FulltextSearch", reflect.TypeOf((*MockInstanceClient)(nil).FulltextSearch), arg0, arg1)
}

// GetDefaultValueTemplate mocks base method.
func (m *MockInstanceClient) GetDefaultValueTemplate(arg0 context.Context, arg1 *instance.GetDefaultValueTemplateRequest) (*types.Struct, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDefaultValueTemplate", arg0, arg1)
	ret0, _ := ret[0].(*types.Struct)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDefaultValueTemplate indicates an expected call of GetDefaultValueTemplate.
func (mr *MockInstanceClientMockRecorder) GetDefaultValueTemplate(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDefaultValueTemplate", reflect.TypeOf((*MockInstanceClient)(nil).GetDefaultValueTemplate), arg0, arg1)
}

// GetDetail mocks base method.
func (m *MockInstanceClient) GetDetail(arg0 context.Context, arg1 *instance.GetDetailRequest) (*types.Struct, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDetail", arg0, arg1)
	ret0, _ := ret[0].(*types.Struct)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDetail indicates an expected call of GetDetail.
func (mr *MockInstanceClientMockRecorder) GetDetail(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDetail", reflect.TypeOf((*MockInstanceClient)(nil).GetDetail), arg0, arg1)
}

// GetInstanceQueryStrategy mocks base method.
func (m *MockInstanceClient) GetInstanceQueryStrategy(arg0 context.Context, arg1 *instance.GetInstanceQueryStrategyRequest) (*cmdb.InstanceQueryStrategy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInstanceQueryStrategy", arg0, arg1)
	ret0, _ := ret[0].(*cmdb.InstanceQueryStrategy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInstanceQueryStrategy indicates an expected call of GetInstanceQueryStrategy.
func (mr *MockInstanceClientMockRecorder) GetInstanceQueryStrategy(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInstanceQueryStrategy", reflect.TypeOf((*MockInstanceClient)(nil).GetInstanceQueryStrategy), arg0, arg1)
}

// GroupInstance mocks base method.
func (m *MockInstanceClient) GroupInstance(arg0 context.Context, arg1 *instance.GroupInstanceRequest) (*instance.GroupInstanceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GroupInstance", arg0, arg1)
	ret0, _ := ret[0].(*instance.GroupInstanceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GroupInstance indicates an expected call of GroupInstance.
func (mr *MockInstanceClientMockRecorder) GroupInstance(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GroupInstance", reflect.TypeOf((*MockInstanceClient)(nil).GroupInstance), arg0, arg1)
}

// GroupInstanceForHoneycomb mocks base method.
func (m *MockInstanceClient) GroupInstanceForHoneycomb(arg0 context.Context, arg1 *instance.GroupInstanceForHoneycombRequest) (*instance.GroupInstanceForHoneycombResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GroupInstanceForHoneycomb", arg0, arg1)
	ret0, _ := ret[0].(*instance.GroupInstanceForHoneycombResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GroupInstanceForHoneycomb indicates an expected call of GroupInstanceForHoneycomb.
func (mr *MockInstanceClientMockRecorder) GroupInstanceForHoneycomb(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GroupInstanceForHoneycomb", reflect.TypeOf((*MockInstanceClient)(nil).GroupInstanceForHoneycomb), arg0, arg1)
}

// GroupInstanceV2 mocks base method.
func (m *MockInstanceClient) GroupInstanceV2(arg0 context.Context, arg1 *instance.GroupInstanceV2Request) (*instance.GroupInstanceV2Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GroupInstanceV2", arg0, arg1)
	ret0, _ := ret[0].(*instance.GroupInstanceV2Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GroupInstanceV2 indicates an expected call of GroupInstanceV2.
func (mr *MockInstanceClientMockRecorder) GroupInstanceV2(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GroupInstanceV2", reflect.TypeOf((*MockInstanceClient)(nil).GroupInstanceV2), arg0, arg1)
}

// GroupInstanceV3 mocks base method.
func (m *MockInstanceClient) GroupInstanceV3(arg0 context.Context, arg1 *instance.GroupInstanceV3Request) (*instance.GroupInstanceV3Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GroupInstanceV3", arg0, arg1)
	ret0, _ := ret[0].(*instance.GroupInstanceV3Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GroupInstanceV3 indicates an expected call of GroupInstanceV3.
func (mr *MockInstanceClientMockRecorder) GroupInstanceV3(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GroupInstanceV3", reflect.TypeOf((*MockInstanceClient)(nil).GroupInstanceV3), arg0, arg1)
}

// ImportInstance mocks base method.
func (m *MockInstanceClient) ImportInstance(arg0 context.Context, arg1 *instance.ImportInstanceRequest) (*instance.ImportInstanceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImportInstance", arg0, arg1)
	ret0, _ := ret[0].(*instance.ImportInstanceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ImportInstance indicates an expected call of ImportInstance.
func (mr *MockInstanceClientMockRecorder) ImportInstance(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImportInstance", reflect.TypeOf((*MockInstanceClient)(nil).ImportInstance), arg0, arg1)
}

// InstancePreviousSnapshot mocks base method.
func (m *MockInstanceClient) InstancePreviousSnapshot(arg0 context.Context, arg1 *instance.InstancePreviousSnapshotRequest) (*types.Struct, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InstancePreviousSnapshot", arg0, arg1)
	ret0, _ := ret[0].(*types.Struct)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InstancePreviousSnapshot indicates an expected call of InstancePreviousSnapshot.
func (mr *MockInstanceClientMockRecorder) InstancePreviousSnapshot(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InstancePreviousSnapshot", reflect.TypeOf((*MockInstanceClient)(nil).InstancePreviousSnapshot), arg0, arg1)
}

// InstanceRelationsCount mocks base method.
func (m *MockInstanceClient) InstanceRelationsCount(arg0 context.Context, arg1 *instance.InstanceRelationsCountRequest) (*types.Struct, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InstanceRelationsCount", arg0, arg1)
	ret0, _ := ret[0].(*types.Struct)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InstanceRelationsCount indicates an expected call of InstanceRelationsCount.
func (mr *MockInstanceClientMockRecorder) InstanceRelationsCount(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InstanceRelationsCount", reflect.TypeOf((*MockInstanceClient)(nil).InstanceRelationsCount), arg0, arg1)
}

// InstanceSnapshot mocks base method.
func (m *MockInstanceClient) InstanceSnapshot(arg0 context.Context, arg1 *instance.InstanceSnapshotRequest) (*types.Struct, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InstanceSnapshot", arg0, arg1)
	ret0, _ := ret[0].(*types.Struct)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InstanceSnapshot indicates an expected call of InstanceSnapshot.
func (mr *MockInstanceClientMockRecorder) InstanceSnapshot(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InstanceSnapshot", reflect.TypeOf((*MockInstanceClient)(nil).InstanceSnapshot), arg0, arg1)
}

// ListInstance mocks base method.
func (m *MockInstanceClient) ListInstance(arg0 context.Context, arg1 *instance.ListInstanceRequest) (*instance.ListInstanceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListInstance", arg0, arg1)
	ret0, _ := ret[0].(*instance.ListInstanceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInstance indicates an expected call of ListInstance.
func (mr *MockInstanceClientMockRecorder) ListInstance(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInstance", reflect.TypeOf((*MockInstanceClient)(nil).ListInstance), arg0, arg1)
}

// ListInstanceQueryStrategy mocks base method.
func (m *MockInstanceClient) ListInstanceQueryStrategy(arg0 context.Context, arg1 *instance.ListInstanceQueryStrategyRequest) (*instance.ListInstanceQueryStrategyResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListInstanceQueryStrategy", arg0, arg1)
	ret0, _ := ret[0].(*instance.ListInstanceQueryStrategyResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInstanceQueryStrategy indicates an expected call of ListInstanceQueryStrategy.
func (mr *MockInstanceClientMockRecorder) ListInstanceQueryStrategy(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInstanceQueryStrategy", reflect.TypeOf((*MockInstanceClient)(nil).ListInstanceQueryStrategy), arg0, arg1)
}

// MixCreateInstance mocks base method.
func (m *MockInstanceClient) MixCreateInstance(arg0 context.Context, arg1 *instance.MixCreateInstanceRequest) (*instance.MixCreateInstanceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MixCreateInstance", arg0, arg1)
	ret0, _ := ret[0].(*instance.MixCreateInstanceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MixCreateInstance indicates an expected call of MixCreateInstance.
func (mr *MockInstanceClientMockRecorder) MixCreateInstance(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MixCreateInstance", reflect.TypeOf((*MockInstanceClient)(nil).MixCreateInstance), arg0, arg1)
}

// MixDeleteInstance mocks base method.
func (m *MockInstanceClient) MixDeleteInstance(arg0 context.Context, arg1 *instance.MixDeleteInstanceRequest) (*types.Empty, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MixDeleteInstance", arg0, arg1)
	ret0, _ := ret[0].(*types.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MixDeleteInstance indicates an expected call of MixDeleteInstance.
func (mr *MockInstanceClientMockRecorder) MixDeleteInstance(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MixDeleteInstance", reflect.TypeOf((*MockInstanceClient)(nil).MixDeleteInstance), arg0, arg1)
}

// MixUpdateInstance mocks base method.
func (m *MockInstanceClient) MixUpdateInstance(arg0 context.Context, arg1 *instance.MixUpdateInstanceRequest) (*types.Empty, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MixUpdateInstance", arg0, arg1)
	ret0, _ := ret[0].(*types.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MixUpdateInstance indicates an expected call of MixUpdateInstance.
func (mr *MockInstanceClientMockRecorder) MixUpdateInstance(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MixUpdateInstance", reflect.TypeOf((*MockInstanceClient)(nil).MixUpdateInstance), arg0, arg1)
}

// ParseSearchQueryStrategy mocks base method.
func (m *MockInstanceClient) ParseSearchQueryStrategy(arg0 context.Context, arg1 *instance.ParseSearchQueryStrategyRequest) (*instance.ParseSearchQueryStrategyResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseSearchQueryStrategy", arg0, arg1)
	ret0, _ := ret[0].(*instance.ParseSearchQueryStrategyResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseSearchQueryStrategy indicates an expected call of ParseSearchQueryStrategy.
func (mr *MockInstanceClientMockRecorder) ParseSearchQueryStrategy(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseSearchQueryStrategy", reflect.TypeOf((*MockInstanceClient)(nil).ParseSearchQueryStrategy), arg0, arg1)
}

// PostSearch mocks base method.
func (m *MockInstanceClient) PostSearch(arg0 context.Context, arg1 *instance.PostSearchRequest) (*instance.PostSearchResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostSearch", arg0, arg1)
	ret0, _ := ret[0].(*instance.PostSearchResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostSearch indicates an expected call of PostSearch.
func (mr *MockInstanceClientMockRecorder) PostSearch(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostSearch", reflect.TypeOf((*MockInstanceClient)(nil).PostSearch), arg0, arg1)
}

// PostSearchV2 mocks base method.
func (m *MockInstanceClient) PostSearchV2(arg0 context.Context, arg1 *instance.PostSearchV2Request) (*instance.PostSearchV2Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostSearchV2", arg0, arg1)
	ret0, _ := ret[0].(*instance.PostSearchV2Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostSearchV2 indicates an expected call of PostSearchV2.
func (mr *MockInstanceClientMockRecorder) PostSearchV2(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostSearchV2", reflect.TypeOf((*MockInstanceClient)(nil).PostSearchV2), arg0, arg1)
}

// PostSearchV3 mocks base method.
func (m *MockInstanceClient) PostSearchV3(arg0 context.Context, arg1 *instance.PostSearchV3Request) (*instance.PostSearchV3Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostSearchV3", arg0, arg1)
	ret0, _ := ret[0].(*instance.PostSearchV3Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostSearchV3 indicates an expected call of PostSearchV3.
func (mr *MockInstanceClientMockRecorder) PostSearchV3(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostSearchV3", reflect.TypeOf((*MockInstanceClient)(nil).PostSearchV3), arg0, arg1)
}

// RelationCountAggregate mocks base method.
func (m *MockInstanceClient) RelationCountAggregate(arg0 context.Context, arg1 *instance.RelationCountAggregateRequest) (*instance.RelationCountAggregateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RelationCountAggregate", arg0, arg1)
	ret0, _ := ret[0].(*instance.RelationCountAggregateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RelationCountAggregate indicates an expected call of RelationCountAggregate.
func (mr *MockInstanceClientMockRecorder) RelationCountAggregate(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RelationCountAggregate", reflect.TypeOf((*MockInstanceClient)(nil).RelationCountAggregate), arg0, arg1)
}

// RelationMaxCheck mocks base method.
func (m *MockInstanceClient) RelationMaxCheck(arg0 context.Context, arg1 *instance.RelationMaxCheckRequest) (*instance.RelationMaxCheckResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RelationMaxCheck", arg0, arg1)
	ret0, _ := ret[0].(*instance.RelationMaxCheckResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RelationMaxCheck indicates an expected call of RelationMaxCheck.
func (mr *MockInstanceClientMockRecorder) RelationMaxCheck(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RelationMaxCheck", reflect.TypeOf((*MockInstanceClient)(nil).RelationMaxCheck), arg0, arg1)
}

// SearchTotal mocks base method.
func (m *MockInstanceClient) SearchTotal(arg0 context.Context, arg1 *instance.SearchTotalRequest) (*instance.SearchTotalResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchTotal", arg0, arg1)
	ret0, _ := ret[0].(*instance.SearchTotalResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchTotal indicates an expected call of SearchTotal.
func (mr *MockInstanceClientMockRecorder) SearchTotal(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchTotal", reflect.TypeOf((*MockInstanceClient)(nil).SearchTotal), arg0, arg1)
}

// UpdateByQuery mocks base method.
func (m *MockInstanceClient) UpdateByQuery(arg0 context.Context, arg1 *instance.UpdateByQueryRequest) (*instance.UpdateByQueryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByQuery", arg0, arg1)
	ret0, _ := ret[0].(*instance.UpdateByQueryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateByQuery indicates an expected call of UpdateByQuery.
func (mr *MockInstanceClientMockRecorder) UpdateByQuery(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByQuery", reflect.TypeOf((*MockInstanceClient)(nil).UpdateByQuery), arg0, arg1)
}

// UpdateInstance mocks base method.
func (m *MockInstanceClient) UpdateInstance(arg0 context.Context, arg1 *instance.UpdateInstanceRequest) (*types.Struct, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateInstance", arg0, arg1)
	ret0, _ := ret[0].(*types.Struct)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateInstance indicates an expected call of UpdateInstance.
func (mr *MockInstanceClientMockRecorder) UpdateInstance(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateInstance", reflect.TypeOf((*MockInstanceClient)(nil).UpdateInstance), arg0, arg1)
}

// UpdateInstanceQueryStrategy mocks base method.
func (m *MockInstanceClient) UpdateInstanceQueryStrategy(arg0 context.Context, arg1 *instance.UpdateInstanceQueryStrategyRequest) (*cmdb.InstanceQueryStrategy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateInstanceQueryStrategy", arg0, arg1)
	ret0, _ := ret[0].(*cmdb.InstanceQueryStrategy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateInstanceQueryStrategy indicates an expected call of UpdateInstanceQueryStrategy.
func (mr *MockInstanceClientMockRecorder) UpdateInstanceQueryStrategy(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateInstanceQueryStrategy", reflect.TypeOf((*MockInstanceClient)(nil).UpdateInstanceQueryStrategy), arg0, arg1)
}

// UpdateInstanceV2 mocks base method.
func (m *MockInstanceClient) UpdateInstanceV2(arg0 context.Context, arg1 *instance.UpdateInstanceV2Request) (*types.Struct, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateInstanceV2", arg0, arg1)
	ret0, _ := ret[0].(*types.Struct)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateInstanceV2 indicates an expected call of UpdateInstanceV2.
func (mr *MockInstanceClientMockRecorder) UpdateInstanceV2(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateInstanceV2", reflect.TypeOf((*MockInstanceClient)(nil).UpdateInstanceV2), arg0, arg1)
}

// UpdatePermissionBatch mocks base method.
func (m *MockInstanceClient) UpdatePermissionBatch(arg0 context.Context, arg1 *instance.UpdatePermissionBatchRequest) (*instance.UpdatePermissionBatchResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePermissionBatch", arg0, arg1)
	ret0, _ := ret[0].(*instance.UpdatePermissionBatchResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePermissionBatch indicates an expected call of UpdatePermissionBatch.
func (mr *MockInstanceClientMockRecorder) UpdatePermissionBatch(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePermissionBatch", reflect.TypeOf((*MockInstanceClient)(nil).UpdatePermissionBatch), arg0, arg1)
}

// UpsertInstance mocks base method.
func (m *MockInstanceClient) UpsertInstance(arg0 context.Context, arg1 *instance.UpsertInstanceRequest) (*instance.UpsertInstanceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertInstance", arg0, arg1)
	ret0, _ := ret[0].(*instance.UpsertInstanceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertInstance indicates an expected call of UpsertInstance.
func (mr *MockInstanceClientMockRecorder) UpsertInstance(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertInstance", reflect.TypeOf((*MockInstanceClient)(nil).UpsertInstance), arg0, arg1)
}

// ValidateInstance mocks base method.
func (m *MockInstanceClient) ValidateInstance(arg0 context.Context, arg1 *instance.ValidateInstanceRequest) (*instance.ValidateInstanceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateInstance", arg0, arg1)
	ret0, _ := ret[0].(*instance.ValidateInstanceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateInstance indicates an expected call of ValidateInstance.
func (mr *MockInstanceClientMockRecorder) ValidateInstance(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateInstance", reflect.TypeOf((*MockInstanceClient)(nil).ValidateInstance), arg0, arg1)
}
