// Code generated by giraffe-go. DO NOT EDIT.
package validators

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"go.easyops.local/fintech_data/internal/apierrors"
	"reflect"
	"strconv"

	"github.com/asaskevich/govalidator"
	"github.com/gin-gonic/gin"
	types "github.com/gogo/protobuf/types"
	giraffe_validators "go.easyops.local/giraffe/pkg/validators"
	"go.easyops.local/kit/gogoprotobuf/jsonpb"
	"go.easyops.local/kit/protobuf/protostruct"
	logctx "go.easyops.local/slog/context"

	message "go.easyops.local/contracts/protorepo-fintech_data/history"
)

var _ = gin.Bind
var _ = logctx.MustGetLogger
var _ = apierrors.ErrAborted
var _ = fmt.Printf
var _ = errors.New
var _ = bytes.Compare
var _ = strconv.Atoi
var _ = govalidator.Matches
var _ = json.Marshal
var _ = jsonpb.Marshaler{}
var _ = protostruct.ToStruct
var _ = reflect.ValueOf
var _ = types.Struct{}
var _ = giraffe_validators.ValidateConstraints

func ValidateExportReportInstance(ctx *gin.Context) (*message.ExportReportInstanceRequest, error) {
	logger := logctx.MustGetLogger(ctx.Request.Context())
	var _ = logger

	request := &message.ExportReportInstanceRequest{}
	var err error

	jsonpbUnmarshaler := jsonpb.Unmarshaler{}
	var buf []byte
	buf, err = ctx.GetRawData()
	if err != nil {
		logger.Errorf("get raw data error, e=%s", err.Error())
		return nil, apierrors.NewErrorInvalidArgument(fmt.Sprintf("获取body数据失败，错误详情:%s", err.Error()))
	}
	// POST, PATCH, PUT请求
	buf, err = giraffe_validators.ValidatePostRequiredAndSetDefault(ctx, buf,
		[]string{},
		map[string]interface{}{},
		ExportReportInstanceValidateTree,
	)
	if err != nil {
		logger.Errorf("jsonpb unmarshal error, e=%s", err.Error())
		return nil, err
	}
	if len(buf) > 0 {
		err = jsonpbUnmarshaler.UnmarshalFromString(string(buf), request)

		if err != nil {
			logger.Errorf("jsonpb unmarshal error, e=%s", err.Error())
			return nil, apierrors.NewErrorInvalidArgument(fmt.Sprintf("json解析失败，错误详情:%s", err.Error()))
		}
	}
	return request, err
}
func ValidateExportReportTask(ctx *gin.Context) (*message.ExportReportTaskRequest, error) {
	logger := logctx.MustGetLogger(ctx.Request.Context())
	var _ = logger

	request := &message.ExportReportTaskRequest{}
	var err error

	jsonpbUnmarshaler := jsonpb.Unmarshaler{}
	var buf []byte
	buf, err = ctx.GetRawData()
	if err != nil {
		logger.Errorf("get raw data error, e=%s", err.Error())
		return nil, apierrors.NewErrorInvalidArgument(fmt.Sprintf("获取body数据失败，错误详情:%s", err.Error()))
	}
	// POST, PATCH, PUT请求
	buf, err = giraffe_validators.ValidatePostRequiredAndSetDefault(ctx, buf,
		[]string{},
		map[string]interface{}{},
		ExportReportTaskValidateTree,
	)
	if err != nil {
		logger.Errorf("jsonpb unmarshal error, e=%s", err.Error())
		return nil, err
	}
	if len(buf) > 0 {
		err = jsonpbUnmarshaler.UnmarshalFromString(string(buf), request)

		if err != nil {
			logger.Errorf("jsonpb unmarshal error, e=%s", err.Error())
			return nil, apierrors.NewErrorInvalidArgument(fmt.Sprintf("json解析失败，错误详情:%s", err.Error()))
		}
	}
	return request, err
}
func ValidateGetReportInstanceTotal(ctx *gin.Context) (*message.GetReportInstanceTotalRequest, error) {
	logger := logctx.MustGetLogger(ctx.Request.Context())
	var _ = logger

	request := &message.GetReportInstanceTotalRequest{}
	var err error
	var ok bool
	var _ = ok
	var p string
	var _ = p
	var exists bool
	var _ = exists
	err = giraffe_validators.ValidateQueryConstraints(ctx.Request.URL.Query(), ctx.Params, GetReportInstanceTotalValidateTree)
	if err != nil {
		logger.Errorf("validate error, e=%s", err.Error())
		return nil, err
	}
	err = ctx.BindQuery(request)
	if err != nil {
		logger.Errorf("bind query error, e=%s", err.Error())
		return nil, apierrors.NewErrorInvalidArgument(fmt.Sprintf("获取请求参数失败，错误详情:%s", err.Error()))
	}

	return request, err
}
func ValidateGetReportTask(ctx *gin.Context) (*message.GetReportTaskRequest, error) {
	logger := logctx.MustGetLogger(ctx.Request.Context())
	var _ = logger

	request := &message.GetReportTaskRequest{}
	var err error
	var ok bool
	var _ = ok
	var p string
	var _ = p
	var exists bool
	var _ = exists
	err = giraffe_validators.ValidateQueryConstraints(ctx.Request.URL.Query(), ctx.Params, GetReportTaskValidateTree)
	if err != nil {
		logger.Errorf("validate error, e=%s", err.Error())
		return nil, err
	}
	err = ctx.BindQuery(request)
	if err != nil {
		logger.Errorf("bind query error, e=%s", err.Error())
		return nil, apierrors.NewErrorInvalidArgument(fmt.Sprintf("获取请求参数失败，错误详情:%s", err.Error()))
	}

	// uri参数
	request.TaskId = ctx.Param("taskId")
	if request.TaskId == "" {
		logger.Error("Required param taskId not exists")
		return nil, errors.New("taskId参数不存在")
	}
	return request, err
}
func ValidateHandleReportInstance(ctx *gin.Context) (*message.HandlReportInstanceRequest, error) {
	logger := logctx.MustGetLogger(ctx.Request.Context())
	var _ = logger

	request := &message.HandlReportInstanceRequest{}
	var err error

	jsonpbUnmarshaler := jsonpb.Unmarshaler{}
	var buf []byte
	buf, err = ctx.GetRawData()
	if err != nil {
		logger.Errorf("get raw data error, e=%s", err.Error())
		return nil, apierrors.NewErrorInvalidArgument(fmt.Sprintf("获取body数据失败，错误详情:%s", err.Error()))
	}
	// POST, PATCH, PUT请求
	buf, err = giraffe_validators.ValidatePostRequiredAndSetDefault(ctx, buf,
		[]string{"dataId"},
		map[string]interface{}{},
		HandleReportInstanceValidateTree,
	)
	if err != nil {
		logger.Errorf("jsonpb unmarshal error, e=%s", err.Error())
		return nil, err
	}
	if len(buf) > 0 {
		err = jsonpbUnmarshaler.UnmarshalFromString(string(buf), request)

		if err != nil {
			logger.Errorf("jsonpb unmarshal error, e=%s", err.Error())
			return nil, apierrors.NewErrorInvalidArgument(fmt.Sprintf("json解析失败，错误详情:%s", err.Error()))
		}
	}
	return request, err
}
func ValidateLastReportTask(ctx *gin.Context) (*message.LastReportTaskRequest, error) {
	logger := logctx.MustGetLogger(ctx.Request.Context())
	var _ = logger

	request := &message.LastReportTaskRequest{}
	var err error
	var ok bool
	var _ = ok
	var p string
	var _ = p
	var exists bool
	var _ = exists
	err = giraffe_validators.ValidateQueryConstraints(ctx.Request.URL.Query(), ctx.Params, LastReportTaskValidateTree)
	if err != nil {
		logger.Errorf("validate error, e=%s", err.Error())
		return nil, err
	}
	err = ctx.BindQuery(request)
	if err != nil {
		logger.Errorf("bind query error, e=%s", err.Error())
		return nil, apierrors.NewErrorInvalidArgument(fmt.Sprintf("获取请求参数失败，错误详情:%s", err.Error()))
	}

	p, exists = ctx.GetQuery("days")
	if !exists {
		_, err = giraffe_validators.SetDefaultValue(request, "Days", reflect.ValueOf(90))
		if err != nil {
			logger.Errorf("set default param days error, err=%s", err.Error())
			return nil, err
		}
	}
	return request, err
}
func ValidateSearchReportBranch(ctx *gin.Context) (*message.SearchReportBranchRequest, error) {
	logger := logctx.MustGetLogger(ctx.Request.Context())
	var _ = logger

	request := &message.SearchReportBranchRequest{}
	var err error

	jsonpbUnmarshaler := jsonpb.Unmarshaler{}
	var buf []byte
	buf, err = ctx.GetRawData()
	if err != nil {
		logger.Errorf("get raw data error, e=%s", err.Error())
		return nil, apierrors.NewErrorInvalidArgument(fmt.Sprintf("获取body数据失败，错误详情:%s", err.Error()))
	}
	// POST, PATCH, PUT请求
	buf, err = giraffe_validators.ValidatePostRequiredAndSetDefault(ctx, buf,
		[]string{"taskId", "st"},
		map[string]interface{}{"page": 1, "page_size": 10},
		SearchReportBranchValidateTree,
	)
	if err != nil {
		logger.Errorf("jsonpb unmarshal error, e=%s", err.Error())
		return nil, err
	}
	if len(buf) > 0 {
		err = jsonpbUnmarshaler.UnmarshalFromString(string(buf), request)

		if err != nil {
			logger.Errorf("jsonpb unmarshal error, e=%s", err.Error())
			return nil, apierrors.NewErrorInvalidArgument(fmt.Sprintf("json解析失败，错误详情:%s", err.Error()))
		}
	}
	return request, err
}
func ValidateSearchReportInstance(ctx *gin.Context) (*message.SearchReportInstanceRequest, error) {
	logger := logctx.MustGetLogger(ctx.Request.Context())
	var _ = logger

	request := &message.SearchReportInstanceRequest{}
	var err error

	jsonpbUnmarshaler := jsonpb.Unmarshaler{}
	var buf []byte
	buf, err = ctx.GetRawData()
	if err != nil {
		logger.Errorf("get raw data error, e=%s", err.Error())
		return nil, apierrors.NewErrorInvalidArgument(fmt.Sprintf("获取body数据失败，错误详情:%s", err.Error()))
	}
	// POST, PATCH, PUT请求
	buf, err = giraffe_validators.ValidatePostRequiredAndSetDefault(ctx, buf,
		[]string{"st"},
		map[string]interface{}{"page": 1, "page_size": 10},
		SearchReportInstanceValidateTree,
	)
	if err != nil {
		logger.Errorf("jsonpb unmarshal error, e=%s", err.Error())
		return nil, err
	}
	if len(buf) > 0 {
		err = jsonpbUnmarshaler.UnmarshalFromString(string(buf), request)

		if err != nil {
			logger.Errorf("jsonpb unmarshal error, e=%s", err.Error())
			return nil, apierrors.NewErrorInvalidArgument(fmt.Sprintf("json解析失败，错误详情:%s", err.Error()))
		}
	}
	return request, err
}
func ValidateSearchReportTask(ctx *gin.Context) (*message.SearchReportTaskRequest, error) {
	logger := logctx.MustGetLogger(ctx.Request.Context())
	var _ = logger

	request := &message.SearchReportTaskRequest{}
	var err error

	jsonpbUnmarshaler := jsonpb.Unmarshaler{}
	var buf []byte
	buf, err = ctx.GetRawData()
	if err != nil {
		logger.Errorf("get raw data error, e=%s", err.Error())
		return nil, apierrors.NewErrorInvalidArgument(fmt.Sprintf("获取body数据失败，错误详情:%s", err.Error()))
	}
	// POST, PATCH, PUT请求
	buf, err = giraffe_validators.ValidatePostRequiredAndSetDefault(ctx, buf,
		[]string{},
		map[string]interface{}{"page": 1, "page_size": 10},
		SearchReportTaskValidateTree,
	)
	if err != nil {
		logger.Errorf("jsonpb unmarshal error, e=%s", err.Error())
		return nil, err
	}
	if len(buf) > 0 {
		err = jsonpbUnmarshaler.UnmarshalFromString(string(buf), request)

		if err != nil {
			logger.Errorf("jsonpb unmarshal error, e=%s", err.Error())
			return nil, apierrors.NewErrorInvalidArgument(fmt.Sprintf("json解析失败，错误详情:%s", err.Error()))
		}
	}
	return request, err
}
