// Code generated by MockGen. DO NOT EDIT.
// Source: go.easyops.local/contracts/protorepo-data_exchange/store (interfaces: Client)

// Package data_exchange is a generated GoMock package.
package data_exchange

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	store "go.easyops.local/contracts/protorepo-data_exchange/store"
)

// MockStoreClient is a mock of Client interface
type MockStoreClient struct {
	ctrl     *gomock.Controller
	recorder *MockStoreClientMockRecorder
}

// MockStoreClientMockRecorder is the mock recorder for MockStoreClient
type MockStoreClientMockRecorder struct {
	mock *MockStoreClient
}

// NewMockStoreClient creates a new mock instance
func NewMockStoreClient(ctrl *gomock.Controller) *MockStoreClient {
	mock := &MockStoreClient{ctrl: ctrl}
	mock.recorder = &MockStoreClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockStoreClient) EXPECT() *MockStoreClientMockRecorder {
	return m.recorder
}

// ClickHouseInsertData mocks base method
func (m *MockStoreClient) ClickHouseInsertData(arg0 context.Context, arg1 *store.ClickHouseInsertDataRequest) (*store.ClickHouseInsertDataResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClickHouseInsertData", arg0, arg1)
	ret0, _ := ret[0].(*store.ClickHouseInsertDataResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClickHouseInsertData indicates an expected call of ClickHouseInsertData
func (mr *MockStoreClientMockRecorder) ClickHouseInsertData(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClickHouseInsertData", reflect.TypeOf((*MockStoreClient)(nil).ClickHouseInsertData), arg0, arg1)
}

// FrontendStat mocks base method
func (m *MockStoreClient) FrontendStat(arg0 context.Context, arg1 *store.FrontendStatRequest) (*store.FrontendStatResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FrontendStat", arg0, arg1)
	ret0, _ := ret[0].(*store.FrontendStatResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FrontendStat indicates an expected call of FrontendStat
func (mr *MockStoreClientMockRecorder) FrontendStat(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FrontendStat", reflect.TypeOf((*MockStoreClient)(nil).FrontendStat), arg0, arg1)
}
