// Code generated by giraffe-go. DO NOT EDIT.
package validators

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"reflect"
	"strconv"

	"go.easyops.local/fintech_data/internal/apierrors"

	"github.com/asaskevich/govalidator"
	"github.com/gin-gonic/gin"
	types "github.com/gogo/protobuf/types"

	giraffe_validators "go.easyops.local/giraffe/pkg/validators"
	"go.easyops.local/kit/gogoprotobuf/jsonpb"
	"go.easyops.local/kit/protobuf/protostruct"
	logctx "go.easyops.local/slog/context"
)

var _ = gin.Bind
var _ = logctx.MustGetLogger
var _ = apierrors.ErrAborted
var _ = fmt.Printf
var _ = errors.New
var _ = bytes.Compare
var _ = strconv.Atoi
var _ = govalidator.Matches
var _ = json.Marshal
var _ = jsonpb.Marshaler{}
var _ = protostruct.ToStruct
var _ = reflect.ValueOf
var _ = types.Struct{}
var _ = giraffe_validators.ValidateConstraints
