// Code generated by MockGen. DO NOT EDIT.
// Source: go.easyops.local/fintech_data/internal/report_rule (interfaces: Service)

// Package report_rule is a generated GoMock package.
package report_rule

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	fintech_data "go.easyops.local/contracts/protorepo-models/easyops/model/fintech_data"
)

// MockService is a mock of Service interface
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetRule mocks base method
func (m *MockService) GetRule(arg0 context.Context, arg1 string) (*fintech_data.ReportObjectConf, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRule", arg0, arg1)
	ret0, _ := ret[0].(*fintech_data.ReportObjectConf)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRule indicates an expected call of GetRule
func (mr *MockServiceMockRecorder) GetRule(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRule", reflect.TypeOf((*MockService)(nil).GetRule), arg0, arg1)
}

// SearchRule mocks base method
func (m *MockService) SearchRule(arg0 context.Context, arg1 map[string]interface{}, arg2 []string) ([]*fintech_data.ReportObjectConf, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchRule", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*fintech_data.ReportObjectConf)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchRule indicates an expected call of SearchRule
func (mr *MockServiceMockRecorder) SearchRule(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchRule", reflect.TypeOf((*MockService)(nil).SearchRule), arg0, arg1, arg2)
}

// UpdateRule mocks base method
func (m *MockService) UpdateRule(arg0 context.Context, arg1 string, arg2 *fintech_data.ReportObjectConf, arg3 []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRule", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRule indicates an expected call of UpdateRule
func (mr *MockServiceMockRecorder) UpdateRule(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRule", reflect.TypeOf((*MockService)(nil).UpdateRule), arg0, arg1, arg2, arg3)
}

// UpdateRuleByQuery mocks base method
func (m *MockService) UpdateRuleByQuery(arg0 context.Context, arg1 map[string]interface{}, arg2 *fintech_data.ReportObjectConf, arg3 []string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRuleByQuery", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateRuleByQuery indicates an expected call of UpdateRuleByQuery
func (mr *MockServiceMockRecorder) UpdateRuleByQuery(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRuleByQuery", reflect.TypeOf((*MockService)(nil).UpdateRuleByQuery), arg0, arg1, arg2, arg3)
}
