// Code generated by MockGen. DO NOT EDIT.
// Source: go.easyops.local/fintech_data/internal/history (interfaces: ObjectStat)

// Package history is a generated GoMock package.
package history

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	history "go.easyops.local/fintech_data/internal/history"
)

// MockObjectStat is a mock of ObjectStat interface
type MockObjectStat struct {
	ctrl     *gomock.Controller
	recorder *MockObjectStatMockRecorder
}

// MockObjectStatMockRecorder is the mock recorder for MockObjectStat
type MockObjectStatMockRecorder struct {
	mock *MockObjectStat
}

// NewMockObjectStat creates a new mock instance
func NewMockObjectStat(ctrl *gomock.Controller) *MockObjectStat {
	mock := &MockObjectStat{ctrl: ctrl}
	mock.recorder = &MockObjectStatMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockObjectStat) EXPECT() *MockObjectStatMockRecorder {
	return m.recorder
}

// Get mocks base method
func (m *MockObjectStat) Get(arg0 context.Context, arg1 string) (*history.StatData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*history.StatData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get
func (mr *MockObjectStatMockRecorder) Get(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockObjectStat)(nil).Get), arg0, arg1)
}

// SearchAll mocks base method
func (m *MockObjectStat) SearchAll(arg0 context.Context, arg1 map[string]interface{}) ([]*history.StatData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchAll", arg0, arg1)
	ret0, _ := ret[0].([]*history.StatData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchAll indicates an expected call of SearchAll
func (mr *MockObjectStatMockRecorder) SearchAll(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchAll", reflect.TypeOf((*MockObjectStat)(nil).SearchAll), arg0, arg1)
}

// Upsert mocks base method
func (m *MockObjectStat) Upsert(arg0 context.Context, arg1 ...*history.StatData) (*history.ChangeInfo, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Upsert", varargs...)
	ret0, _ := ret[0].(*history.ChangeInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upsert indicates an expected call of Upsert
func (mr *MockObjectStatMockRecorder) Upsert(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockObjectStat)(nil).Upsert), varargs...)
}
