// Code generated by MockGen. DO NOT EDIT.
// Source: go.easyops.local/fintech_data/internal/history (interfaces: TaskHistory)

// Package history is a generated GoMock package.
package history

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	fintech_data "go.easyops.local/contracts/protorepo-models/easyops/model/fintech_data"
	monthly_collection_service "go.easyops.local/contracts/protorepo-models/easyops/model/monthly_collection_service"
	history "go.easyops.local/fintech_data/internal/history"
)

// MockTaskHistory is a mock of TaskHistory interface
type MockTaskHistory struct {
	ctrl     *gomock.Controller
	recorder *MockTaskHistoryMockRecorder
}

// MockTaskHistoryMockRecorder is the mock recorder for MockTaskHistory
type MockTaskHistoryMockRecorder struct {
	mock *MockTaskHistory
}

// NewMockTaskHistory creates a new mock instance
func NewMockTaskHistory(ctrl *gomock.Controller) *MockTaskHistory {
	mock := &MockTaskHistory{ctrl: ctrl}
	mock.recorder = &MockTaskHistoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockTaskHistory) EXPECT() *MockTaskHistoryMockRecorder {
	return m.recorder
}

// BatchCreateBranch mocks base method
func (m *MockTaskHistory) BatchCreateBranch(arg0 context.Context, arg1 []*fintech_data.ReportBranch) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchCreateBranch", arg0, arg1)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchCreateBranch indicates an expected call of BatchCreateBranch
func (mr *MockTaskHistoryMockRecorder) BatchCreateBranch(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchCreateBranch", reflect.TypeOf((*MockTaskHistory)(nil).BatchCreateBranch), arg0, arg1)
}

// BatchCreateInstance mocks base method
func (m *MockTaskHistory) BatchCreateInstance(arg0 context.Context, arg1 []*fintech_data.ReportInstance) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchCreateInstance", arg0, arg1)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchCreateInstance indicates an expected call of BatchCreateInstance
func (mr *MockTaskHistoryMockRecorder) BatchCreateInstance(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchCreateInstance", reflect.TypeOf((*MockTaskHistory)(nil).BatchCreateInstance), arg0, arg1)
}

// CreateBranch mocks base method
func (m *MockTaskHistory) CreateBranch(arg0 context.Context, arg1 *fintech_data.ReportBranch) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBranch", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBranch indicates an expected call of CreateBranch
func (mr *MockTaskHistoryMockRecorder) CreateBranch(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBranch", reflect.TypeOf((*MockTaskHistory)(nil).CreateBranch), arg0, arg1)
}

// CreateTask mocks base method
func (m *MockTaskHistory) CreateTask(arg0 context.Context, arg1 *fintech_data.ReportTask) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTask", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTask indicates an expected call of CreateTask
func (mr *MockTaskHistoryMockRecorder) CreateTask(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTask", reflect.TypeOf((*MockTaskHistory)(nil).CreateTask), arg0, arg1)
}

// GetInstance mocks base method
func (m *MockTaskHistory) GetInstance(arg0 context.Context, arg1 string) (*fintech_data.ReportInstance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInstance", arg0, arg1)
	ret0, _ := ret[0].(*fintech_data.ReportInstance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInstance indicates an expected call of GetInstance
func (mr *MockTaskHistoryMockRecorder) GetInstance(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInstance", reflect.TypeOf((*MockTaskHistory)(nil).GetInstance), arg0, arg1)
}

// GetTask mocks base method
func (m *MockTaskHistory) GetTask(arg0 context.Context, arg1 string) (*fintech_data.ReportTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTask", arg0, arg1)
	ret0, _ := ret[0].(*fintech_data.ReportTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTask indicates an expected call of GetTask
func (mr *MockTaskHistoryMockRecorder) GetTask(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTask", reflect.TypeOf((*MockTaskHistory)(nil).GetTask), arg0, arg1)
}

// SearchAllBranch mocks base method
func (m *MockTaskHistory) SearchAllBranch(arg0 context.Context, arg1 []*monthly_collection_service.QueryItem, arg2 map[string]interface{}, arg3, arg4, arg5 int) ([]*fintech_data.ReportBranch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchAllBranch", arg0, arg1, arg2, arg3, arg4, arg5)
	ret0, _ := ret[0].([]*fintech_data.ReportBranch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchAllBranch indicates an expected call of SearchAllBranch
func (mr *MockTaskHistoryMockRecorder) SearchAllBranch(arg0, arg1, arg2, arg3, arg4, arg5 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchAllBranch", reflect.TypeOf((*MockTaskHistory)(nil).SearchAllBranch), arg0, arg1, arg2, arg3, arg4, arg5)
}

// SearchAllTask mocks base method
func (m *MockTaskHistory) SearchAllTask(arg0 context.Context, arg1 []*monthly_collection_service.QueryItem, arg2 map[string]interface{}, arg3, arg4, arg5 int) ([]*fintech_data.ReportTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchAllTask", arg0, arg1, arg2, arg3, arg4, arg5)
	ret0, _ := ret[0].([]*fintech_data.ReportTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchAllTask indicates an expected call of SearchAllTask
func (mr *MockTaskHistoryMockRecorder) SearchAllTask(arg0, arg1, arg2, arg3, arg4, arg5 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchAllTask", reflect.TypeOf((*MockTaskHistory)(nil).SearchAllTask), arg0, arg1, arg2, arg3, arg4, arg5)
}

// SearchBranch mocks base method
func (m *MockTaskHistory) SearchBranch(arg0 context.Context, arg1 []*monthly_collection_service.QueryItem, arg2 map[string]interface{}, arg3, arg4, arg5, arg6 int) ([]*fintech_data.ReportBranch, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchBranch", arg0, arg1, arg2, arg3, arg4, arg5, arg6)
	ret0, _ := ret[0].([]*fintech_data.ReportBranch)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SearchBranch indicates an expected call of SearchBranch
func (mr *MockTaskHistoryMockRecorder) SearchBranch(arg0, arg1, arg2, arg3, arg4, arg5, arg6 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchBranch", reflect.TypeOf((*MockTaskHistory)(nil).SearchBranch), arg0, arg1, arg2, arg3, arg4, arg5, arg6)
}

// SearchInstance mocks base method
func (m *MockTaskHistory) SearchInstance(arg0 context.Context, arg1 []*monthly_collection_service.QueryItem, arg2 map[string]interface{}, arg3, arg4, arg5, arg6 int) ([]*fintech_data.ReportInstance, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchInstance", arg0, arg1, arg2, arg3, arg4, arg5, arg6)
	ret0, _ := ret[0].([]*fintech_data.ReportInstance)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SearchInstance indicates an expected call of SearchInstance
func (mr *MockTaskHistoryMockRecorder) SearchInstance(arg0, arg1, arg2, arg3, arg4, arg5, arg6 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchInstance", reflect.TypeOf((*MockTaskHistory)(nil).SearchInstance), arg0, arg1, arg2, arg3, arg4, arg5, arg6)
}

// SearchInstanceAll mocks base method
func (m *MockTaskHistory) SearchInstanceAll(arg0 context.Context, arg1 []*monthly_collection_service.QueryItem, arg2 map[string]interface{}, arg3, arg4, arg5 int) ([]*fintech_data.ReportInstance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchInstanceAll", arg0, arg1, arg2, arg3, arg4, arg5)
	ret0, _ := ret[0].([]*fintech_data.ReportInstance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchInstanceAll indicates an expected call of SearchInstanceAll
func (mr *MockTaskHistoryMockRecorder) SearchInstanceAll(arg0, arg1, arg2, arg3, arg4, arg5 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchInstanceAll", reflect.TypeOf((*MockTaskHistory)(nil).SearchInstanceAll), arg0, arg1, arg2, arg3, arg4, arg5)
}

// SearchInstanceLimit mocks base method
func (m *MockTaskHistory) SearchInstanceLimit(arg0 context.Context, arg1 []*monthly_collection_service.QueryItem, arg2 map[string]interface{}, arg3, arg4, arg5 int, arg6 string) (*history.InstanceLimitResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchInstanceLimit", arg0, arg1, arg2, arg3, arg4, arg5, arg6)
	ret0, _ := ret[0].(*history.InstanceLimitResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchInstanceLimit indicates an expected call of SearchInstanceLimit
func (mr *MockTaskHistoryMockRecorder) SearchInstanceLimit(arg0, arg1, arg2, arg3, arg4, arg5, arg6 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchInstanceLimit", reflect.TypeOf((*MockTaskHistory)(nil).SearchInstanceLimit), arg0, arg1, arg2, arg3, arg4, arg5, arg6)
}

// SearchOneTask mocks base method
func (m *MockTaskHistory) SearchOneTask(arg0 context.Context, arg1 []*monthly_collection_service.QueryItem, arg2 map[string]interface{}, arg3, arg4 int) (*fintech_data.ReportTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchOneTask", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(*fintech_data.ReportTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchOneTask indicates an expected call of SearchOneTask
func (mr *MockTaskHistoryMockRecorder) SearchOneTask(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchOneTask", reflect.TypeOf((*MockTaskHistory)(nil).SearchOneTask), arg0, arg1, arg2, arg3, arg4)
}

// SearchTask mocks base method
func (m *MockTaskHistory) SearchTask(arg0 context.Context, arg1 []*monthly_collection_service.QueryItem, arg2 map[string]interface{}, arg3, arg4, arg5, arg6 int) ([]*fintech_data.ReportTask, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchTask", arg0, arg1, arg2, arg3, arg4, arg5, arg6)
	ret0, _ := ret[0].([]*fintech_data.ReportTask)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SearchTask indicates an expected call of SearchTask
func (mr *MockTaskHistoryMockRecorder) SearchTask(arg0, arg1, arg2, arg3, arg4, arg5, arg6 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchTask", reflect.TypeOf((*MockTaskHistory)(nil).SearchTask), arg0, arg1, arg2, arg3, arg4, arg5, arg6)
}

// UpdateBranch mocks base method
func (m *MockTaskHistory) UpdateBranch(arg0 context.Context, arg1 string, arg2 *fintech_data.ReportBranch, arg3 []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBranch", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBranch indicates an expected call of UpdateBranch
func (mr *MockTaskHistoryMockRecorder) UpdateBranch(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBranch", reflect.TypeOf((*MockTaskHistory)(nil).UpdateBranch), arg0, arg1, arg2, arg3)
}

// UpdateInstance mocks base method
func (m *MockTaskHistory) UpdateInstance(arg0 context.Context, arg1 string, arg2 *fintech_data.ReportInstance, arg3 []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateInstance", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateInstance indicates an expected call of UpdateInstance
func (mr *MockTaskHistoryMockRecorder) UpdateInstance(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateInstance", reflect.TypeOf((*MockTaskHistory)(nil).UpdateInstance), arg0, arg1, arg2, arg3)
}

// UpdateInstanceByFilter mocks base method
func (m *MockTaskHistory) UpdateInstanceByFilter(arg0 context.Context, arg1 []*monthly_collection_service.QueryItem, arg2 *fintech_data.ReportInstance, arg3 []string, arg4, arg5 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateInstanceByFilter", arg0, arg1, arg2, arg3, arg4, arg5)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateInstanceByFilter indicates an expected call of UpdateInstanceByFilter
func (mr *MockTaskHistoryMockRecorder) UpdateInstanceByFilter(arg0, arg1, arg2, arg3, arg4, arg5 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateInstanceByFilter", reflect.TypeOf((*MockTaskHistory)(nil).UpdateInstanceByFilter), arg0, arg1, arg2, arg3, arg4, arg5)
}

// UpdateTask mocks base method
func (m *MockTaskHistory) UpdateTask(arg0 context.Context, arg1 string, arg2 *fintech_data.ReportTask) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTask", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTask indicates an expected call of UpdateTask
func (mr *MockTaskHistoryMockRecorder) UpdateTask(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTask", reflect.TypeOf((*MockTaskHistory)(nil).UpdateTask), arg0, arg1, arg2)
}
