// Code generated by MockGen. DO NOT EDIT.
// Source: go.easyops.local/fintech_data/internal/history (interfaces: CenterData)

// Package history is a generated GoMock package.
package history

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	history "go.easyops.local/fintech_data/internal/history"
)

// MockCenterData is a mock of CenterData interface
type MockCenterData struct {
	ctrl     *gomock.Controller
	recorder *MockCenterDataMockRecorder
}

// MockCenterDataMockRecorder is the mock recorder for MockCenterData
type MockCenterDataMockRecorder struct {
	mock *MockCenterData
}

// NewMockCenterData creates a new mock instance
func NewMockCenterData(ctrl *gomock.Controller) *MockCenterData {
	mock := &MockCenterData{ctrl: ctrl}
	mock.recorder = &MockCenterDataMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockCenterData) EXPECT() *MockCenterDataMockRecorder {
	return m.recorder
}

// Aggregate mocks base method
func (m *MockCenterData) Aggregate(arg0 context.Context, arg1, arg2 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Aggregate", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Aggregate indicates an expected call of Aggregate
func (mr *MockCenterDataMockRecorder) Aggregate(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Aggregate", reflect.TypeOf((*MockCenterData)(nil).Aggregate), arg0, arg1, arg2)
}

// Count mocks base method
func (m *MockCenterData) Count(arg0 context.Context, arg1 map[string]interface{}) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count
func (mr *MockCenterDataMockRecorder) Count(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockCenterData)(nil).Count), arg0, arg1)
}

// RemoveAll mocks base method
func (m *MockCenterData) RemoveAll(arg0 context.Context, arg1 ...*history.ReportMetaData) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RemoveAll", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveAll indicates an expected call of RemoveAll
func (mr *MockCenterDataMockRecorder) RemoveAll(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveAll", reflect.TypeOf((*MockCenterData)(nil).RemoveAll), varargs...)
}

// SearchAll mocks base method
func (m *MockCenterData) SearchAll(arg0 context.Context, arg1 map[string]interface{}, arg2 []string) ([]*history.ReportMetaData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchAll", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*history.ReportMetaData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchAll indicates an expected call of SearchAll
func (mr *MockCenterDataMockRecorder) SearchAll(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchAll", reflect.TypeOf((*MockCenterData)(nil).SearchAll), arg0, arg1, arg2)
}

// Upsert mocks base method
func (m *MockCenterData) Upsert(arg0 context.Context, arg1 ...*history.ReportMetaData) (*history.ChangeInfo, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Upsert", varargs...)
	ret0, _ := ret[0].(*history.ChangeInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upsert indicates an expected call of Upsert
func (mr *MockCenterDataMockRecorder) Upsert(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockCenterData)(nil).Upsert), varargs...)
}
