// Code generated by MockGen. DO NOT EDIT.
// Source: go.easyops.local/fintech_data/internal/mongo (interfaces: CollectionHelper)

// Package mongo is a generated GoMock package.
package mongo

import (
	reflect "reflect"

	mgo "github.com/globalsign/mgo"
	gomock "github.com/golang/mock/gomock"

	mongo "go.easyops.local/fintech_data/internal/mongo"
)

// MockCollectionHelper is a mock of CollectionHelper interface
type MockCollectionHelper struct {
	ctrl     *gomock.Controller
	recorder *MockCollectionHelperMockRecorder
}

// MockCollectionHelperMockRecorder is the mock recorder for MockCollectionHelper
type MockCollectionHelperMockRecorder struct {
	mock *MockCollectionHelper
}

// NewMockCollectionHelper creates a new mock instance
func NewMockCollectionHelper(ctrl *gomock.Controller) *MockCollectionHelper {
	mock := &MockCollectionHelper{ctrl: ctrl}
	mock.recorder = &MockCollectionHelperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockCollectionHelper) EXPECT() *MockCollectionHelperMockRecorder {
	return m.recorder
}

// Bulk mocks base method
func (m *MockCollectionHelper) Bulk() mongo.BulkHelper {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Bulk")
	ret0, _ := ret[0].(mongo.BulkHelper)
	return ret0
}

// Bulk indicates an expected call of Bulk
func (mr *MockCollectionHelperMockRecorder) Bulk() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Bulk", reflect.TypeOf((*MockCollectionHelper)(nil).Bulk))
}

// Find mocks base method
func (m *MockCollectionHelper) Find(arg0 interface{}) mongo.QueryHelper {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", arg0)
	ret0, _ := ret[0].(mongo.QueryHelper)
	return ret0
}

// Find indicates an expected call of Find
func (mr *MockCollectionHelperMockRecorder) Find(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockCollectionHelper)(nil).Find), arg0)
}

// Insert mocks base method
func (m *MockCollectionHelper) Insert(arg0 ...interface{}) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Insert", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert
func (mr *MockCollectionHelperMockRecorder) Insert(arg0 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockCollectionHelper)(nil).Insert), arg0...)
}

// Pipe mocks base method
func (m *MockCollectionHelper) Pipe(arg0 interface{}) mongo.PipeHelper {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Pipe", arg0)
	ret0, _ := ret[0].(mongo.PipeHelper)
	return ret0
}

// Pipe indicates an expected call of Pipe
func (mr *MockCollectionHelperMockRecorder) Pipe(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pipe", reflect.TypeOf((*MockCollectionHelper)(nil).Pipe), arg0)
}

// Remove mocks base method
func (m *MockCollectionHelper) Remove(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove
func (mr *MockCollectionHelperMockRecorder) Remove(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockCollectionHelper)(nil).Remove), arg0)
}

// Update mocks base method
func (m *MockCollectionHelper) Update(arg0, arg1 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update
func (mr *MockCollectionHelperMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCollectionHelper)(nil).Update), arg0, arg1)
}

// UpdateAll mocks base method
func (m *MockCollectionHelper) UpdateAll(arg0, arg1 interface{}) (*mgo.ChangeInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAll", arg0, arg1)
	ret0, _ := ret[0].(*mgo.ChangeInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAll indicates an expected call of UpdateAll
func (mr *MockCollectionHelperMockRecorder) UpdateAll(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAll", reflect.TypeOf((*MockCollectionHelper)(nil).UpdateAll), arg0, arg1)
}

// Upsert mocks base method
func (m *MockCollectionHelper) Upsert(arg0, arg1 interface{}) (*mgo.ChangeInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", arg0, arg1)
	ret0, _ := ret[0].(*mgo.ChangeInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upsert indicates an expected call of Upsert
func (mr *MockCollectionHelperMockRecorder) Upsert(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockCollectionHelper)(nil).Upsert), arg0, arg1)
}
