// Code generated by MockGen. DO NOT EDIT.
// Source: go.easyops.local/fintech_data/internal/mongo (interfaces: PipeHelper)

// Package mongo is a generated GoMock package.
package mongo

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockPipeHelper is a mock of PipeHelper interface
type MockPipeHelper struct {
	ctrl     *gomock.Controller
	recorder *MockPipeHelperMockRecorder
}

// MockPipeHelperMockRecorder is the mock recorder for MockPipeHelper
type MockPipeHelperMockRecorder struct {
	mock *MockPipeHelper
}

// NewMockPipeHelper creates a new mock instance
func NewMockPipeHelper(ctrl *gomock.Controller) *MockPipeHelper {
	mock := &MockPipeHelper{ctrl: ctrl}
	mock.recorder = &MockPipeHelperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockPipeHelper) EXPECT() *MockPipeHelperMockRecorder {
	return m.recorder
}

// All mocks base method
func (m *MockPipeHelper) All(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "All", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// All indicates an expected call of All
func (mr *MockPipeHelperMockRecorder) All(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "All", reflect.TypeOf((*MockPipeHelper)(nil).All), arg0)
}
