// Code generated by MockGen. DO NOT EDIT.
// Source: go.easyops.local/fintech_data/internal/mongo (interfaces: BulkHelper)

// Package mongo is a generated GoMock package.
package mongo

import (
	reflect "reflect"

	mgo "github.com/globalsign/mgo"
	gomock "github.com/golang/mock/gomock"
)

// MockBulkHelper is a mock of BulkHelper interface
type MockBulkHelper struct {
	ctrl     *gomock.Controller
	recorder *MockBulkHelperMockRecorder
}

// MockBulkHelperMockRecorder is the mock recorder for MockBulkHelper
type MockBulkHelperMockRecorder struct {
	mock *MockBulkHelper
}

// NewMockBulkHelper creates a new mock instance
func NewMockBulkHelper(ctrl *gomock.Controller) *MockBulkHelper {
	mock := &MockBulkHelper{ctrl: ctrl}
	mock.recorder = &MockBulkHelperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockBulkHelper) EXPECT() *MockBulkHelperMockRecorder {
	return m.recorder
}

// Insert mocks base method
func (m *MockBulkHelper) Insert(arg0 ...interface{}) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Insert", varargs...)
}

// Insert indicates an expected call of Insert
func (mr *MockBulkHelperMockRecorder) Insert(arg0 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockBulkHelper)(nil).Insert), arg0...)
}

// Remove mocks base method
func (m *MockBulkHelper) Remove(arg0 ...interface{}) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Remove", varargs...)
}

// Remove indicates an expected call of Remove
func (mr *MockBulkHelperMockRecorder) Remove(arg0 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockBulkHelper)(nil).Remove), arg0...)
}

// RemoveAll mocks base method
func (m *MockBulkHelper) RemoveAll(arg0 ...interface{}) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "RemoveAll", varargs...)
}

// RemoveAll indicates an expected call of RemoveAll
func (mr *MockBulkHelperMockRecorder) RemoveAll(arg0 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveAll", reflect.TypeOf((*MockBulkHelper)(nil).RemoveAll), arg0...)
}

// Run mocks base method
func (m *MockBulkHelper) Run() (*mgo.BulkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run")
	ret0, _ := ret[0].(*mgo.BulkResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Run indicates an expected call of Run
func (mr *MockBulkHelperMockRecorder) Run() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockBulkHelper)(nil).Run))
}

// Upsert mocks base method
func (m *MockBulkHelper) Upsert(arg0 ...interface{}) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Upsert", varargs...)
}

// Upsert indicates an expected call of Upsert
func (mr *MockBulkHelperMockRecorder) Upsert(arg0 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockBulkHelper)(nil).Upsert), arg0...)
}
