// Code generated by MockGen. DO NOT EDIT.
// Source: go.easyops.local/fintech_data/internal/mongo (interfaces: QueryHelper)

// Package mongo is a generated GoMock package.
package mongo

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	mongo "go.easyops.local/fintech_data/internal/mongo"
)

// MockQueryHelper is a mock of QueryHelper interface
type MockQueryHelper struct {
	ctrl     *gomock.Controller
	recorder *MockQueryHelperMockRecorder
}

// MockQueryHelperMockRecorder is the mock recorder for MockQueryHelper
type MockQueryHelperMockRecorder struct {
	mock *MockQueryHelper
}

// NewMockQueryHelper creates a new mock instance
func NewMockQueryHelper(ctrl *gomock.Controller) *MockQueryHelper {
	mock := &MockQueryHelper{ctrl: ctrl}
	mock.recorder = &MockQueryHelperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockQueryHelper) EXPECT() *MockQueryHelperMockRecorder {
	return m.recorder
}

// All mocks base method
func (m *MockQueryHelper) All(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "All", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// All indicates an expected call of All
func (mr *MockQueryHelperMockRecorder) All(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "All", reflect.TypeOf((*MockQueryHelper)(nil).All), arg0)
}

// Count mocks base method
func (m *MockQueryHelper) Count() (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count")
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count
func (mr *MockQueryHelperMockRecorder) Count() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockQueryHelper)(nil).Count))
}

// Limit mocks base method
func (m *MockQueryHelper) Limit(arg0 int) mongo.QueryHelper {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Limit", arg0)
	ret0, _ := ret[0].(mongo.QueryHelper)
	return ret0
}

// Limit indicates an expected call of Limit
func (mr *MockQueryHelperMockRecorder) Limit(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Limit", reflect.TypeOf((*MockQueryHelper)(nil).Limit), arg0)
}

// One mocks base method
func (m *MockQueryHelper) One(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "One", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// One indicates an expected call of One
func (mr *MockQueryHelperMockRecorder) One(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "One", reflect.TypeOf((*MockQueryHelper)(nil).One), arg0)
}

// Select mocks base method
func (m *MockQueryHelper) Select(arg0 interface{}) mongo.QueryHelper {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Select", arg0)
	ret0, _ := ret[0].(mongo.QueryHelper)
	return ret0
}

// Select indicates an expected call of Select
func (mr *MockQueryHelperMockRecorder) Select(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Select", reflect.TypeOf((*MockQueryHelper)(nil).Select), arg0)
}

// Skip mocks base method
func (m *MockQueryHelper) Skip(arg0 int) mongo.QueryHelper {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Skip", arg0)
	ret0, _ := ret[0].(mongo.QueryHelper)
	return ret0
}

// Skip indicates an expected call of Skip
func (mr *MockQueryHelperMockRecorder) Skip(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Skip", reflect.TypeOf((*MockQueryHelper)(nil).Skip), arg0)
}

// Sort mocks base method
func (m *MockQueryHelper) Sort(arg0 ...string) mongo.QueryHelper {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Sort", varargs...)
	ret0, _ := ret[0].(mongo.QueryHelper)
	return ret0
}

// Sort indicates an expected call of Sort
func (mr *MockQueryHelperMockRecorder) Sort(arg0 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sort", reflect.TypeOf((*MockQueryHelper)(nil).Sort), arg0...)
}
