// Code generated by giraffe-go. DO NOT EDIT.
package dashboard

import (
	"github.com/gin-gonic/gin"
	types "github.com/gogo/protobuf/types"

	message "go.easyops.local/contracts/protorepo-fintech_data/dashboard"
	"go.easyops.local/fintech_data/dashboard/validators"
	"go.easyops.local/fintech_data/internal/apierrors"
	"go.easyops.local/kit/gerr"
	kitweb "go.easyops.local/kit/web"
	"go.easyops.local/slog"
	logctx "go.easyops.local/slog/context"
)

var _ kitweb.JSONPb
var _ = apierrors.ErrInvalidArgument
var _ = types.Struct{}
var _ = validators.EmptyTree

type DashboardController struct {
	logger  slog.Logger
	service DashboardService
}

func NewDashboardController(logger slog.Logger, service DashboardService) *DashboardController {
	return &DashboardController{
		logger:  logger,
		service: service,
	}
}

func (s *DashboardController) ExportReportObjectStat(ctx *gin.Context) {
	logger := logctx.MustGetLogger(ctx.Request.Context())
	var _ = logger
	var err error

	request := &types.Empty{}

	builder, err := s.service.ExportReportObjectStat(ctx.Request.Context(), request)
	if err != nil {
		apiError := gerr.ToApiError(err)
		ctx.JSON(apiError.Status(), apiError.Data())
		return
	} else {
		builder.SetHeader(ctx)
		builder.Write(ctx.Writer)
		return
	}
}

func (s *DashboardController) ReportInstanceCount(ctx *gin.Context) {
	logger := logctx.MustGetLogger(ctx.Request.Context())
	var _ = logger
	var err error

	request := &types.Empty{}

	data, err := s.service.ReportInstanceCount(ctx.Request.Context(), request)
	if err != nil {
		apiError := gerr.ToApiError(err)
		ctx.JSON(apiError.Status(), apiError.Data())
		return
	} else {

		ctx.Render(200, kitweb.JSONPb{
			Data: &message.ReportInstanceCountResponseWrapper{
				Data: data,
			},
			UseCustomMarshaler: true,
			UseGogo:            true,
		})
		return

	}
}

func (s *DashboardController) ReportObjectCount(ctx *gin.Context) {
	logger := logctx.MustGetLogger(ctx.Request.Context())
	var _ = logger
	var err error

	request := &types.Empty{}

	data, err := s.service.ReportObjectCount(ctx.Request.Context(), request)
	if err != nil {
		apiError := gerr.ToApiError(err)
		ctx.JSON(apiError.Status(), apiError.Data())
		return
	} else {

		ctx.Render(200, kitweb.JSONPb{
			Data: &message.ReportObjectCountResponseWrapper{
				Data: data,
			},
			UseCustomMarshaler: true,
			UseGogo:            true,
		})
		return

	}
}

func (s *DashboardController) ReportObjectStat(ctx *gin.Context) {
	logger := logctx.MustGetLogger(ctx.Request.Context())
	var _ = logger
	var err error

	request := &types.Empty{}

	data, err := s.service.ReportObjectStat(ctx.Request.Context(), request)
	if err != nil {
		apiError := gerr.ToApiError(err)
		ctx.JSON(apiError.Status(), apiError.Data())
		return
	} else {

		ctx.Render(200, kitweb.JSONPb{
			Data: &message.ReportObjectStatResponseWrapper{
				Data: data,
			},
			UseCustomMarshaler: true,
			UseGogo:            true,
		})
		return

	}
}
