// Code generated by giraffe-go. DO NOT EDIT.
package dashboard

import "github.com/gin-gonic/gin"

func (s *DashboardController) Register(engine *gin.Engine) {
	engine.GET("/api/object/stat/export", s.ExportReportObjectStat)
	engine.GET("/api/report/instance/count", s.ReportInstanceCount)
	engine.GET("/api/report/object/count", s.ReportObjectCount)
	engine.GET("/api/object/stat/list", s.ReportObjectStat)
}
