// Code generated by giraffe-go. DO NOT EDIT.
package dashboard

import (
	"context"

	types "github.com/gogo/protobuf/types"

	message "go.easyops.local/contracts/protorepo-fintech_data/dashboard"
	internaltypes "go.easyops.local/fintech_data/internal/types"
)

var _ = types.Struct{}
var _ = message.NewClient

type DashboardService interface {
	ExportReportObjectStat(ctx context.Context, request *types.Empty) (internaltypes.FileExporter, error)
	ReportInstanceCount(ctx context.Context, request *types.Empty) (*message.ReportInstanceCountResponse, error)
	ReportObjectCount(ctx context.Context, request *types.Empty) (*message.ReportObjectCountResponse, error)
	ReportObjectStat(ctx context.Context, request *types.Empty) (*message.ReportObjectStatResponse, error)
}
