// Code generated by MockGen. DO NOT EDIT.
// Source: go.easyops.local/fintech_data/internal/excelutil (interfaces: Exporter)

// Package excelutil is a generated GoMock package.
package excelutil

import (
	io "io"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	excelutil "go.easyops.local/fintech_data/internal/excelutil"
	types "go.easyops.local/fintech_data/internal/types"
)

// MockExporter is a mock of Exporter interface
type MockExporter struct {
	ctrl     *gomock.Controller
	recorder *MockExporterMockRecorder
}

// MockExporterMockRecorder is the mock recorder for MockExporter
type MockExporterMockRecorder struct {
	mock *MockExporter
}

// NewMockExporter creates a new mock instance
func NewMockExporter(ctrl *gomock.Controller) *MockExporter {
	mock := &MockExporter{ctrl: ctrl}
	mock.recorder = &MockExporterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockExporter) EXPECT() *MockExporterMockRecorder {
	return m.recorder
}

// SetHeader mocks base method
func (m *MockExporter) SetHeader(arg0 types.Header) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetHeader", arg0)
}

// SetHeader indicates an expected call of SetHeader
func (mr *MockExporterMockRecorder) SetHeader(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHeader", reflect.TypeOf((*MockExporter)(nil).SetHeader), arg0)
}

// Write mocks base method
func (m *MockExporter) Write(arg0 io.Writer) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Write indicates an expected call of Write
func (mr *MockExporterMockRecorder) Write(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockExporter)(nil).Write), arg0)
}

// WriteExcelHeader mocks base method
func (m *MockExporter) WriteExcelHeader(arg0 []excelutil.HeaderCell) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteExcelHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteExcelHeader indicates an expected call of WriteExcelHeader
func (mr *MockExporterMockRecorder) WriteExcelHeader(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteExcelHeader", reflect.TypeOf((*MockExporter)(nil).WriteExcelHeader), arg0)
}

// WriteRow mocks base method
func (m *MockExporter) WriteRow(arg0 map[string]interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteRow", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteRow indicates an expected call of WriteRow
func (mr *MockExporterMockRecorder) WriteRow(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteRow", reflect.TypeOf((*MockExporter)(nil).WriteRow), arg0)
}
