// Code generated by MockGen. DO NOT EDIT.
// Source: go.easyops.local/fintech_data/internal/report_instance (interfaces: Service)

// Package report_instance is a generated GoMock package.
package report_instance

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	fintech_data "go.easyops.local/contracts/protorepo-models/easyops/model/fintech_data"
	types "go.easyops.local/fintech_data/internal/types"
)

// MockService is a mock of Service interface
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// SearchReportInstance mocks base method
func (m *MockService) SearchReportInstance(arg0 context.Context, arg1 types.CreateTaskRequest, arg2 *fintech_data.ReportTask) ([]*fintech_data.ReportInstance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchReportInstance", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*fintech_data.ReportInstance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchReportInstance indicates an expected call of SearchReportInstance
func (mr *MockServiceMockRecorder) SearchReportInstance(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchReportInstance", reflect.TypeOf((*MockService)(nil).SearchReportInstance), arg0, arg1, arg2)
}
