// Code generated by MockGen. DO NOT EDIT.
// Source: go.easyops.local/fintech_data/internal/report_task (interfaces: ReportService)

// Package report_task is a generated GoMock package.
package report_task

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	fintech_data "go.easyops.local/contracts/protorepo-models/easyops/model/fintech_data"
	types "go.easyops.local/fintech_data/internal/types"
	reflect "reflect"
)

// MockReportService is a mock of ReportService interface
type MockReportService struct {
	ctrl     *gomock.Controller
	recorder *MockReportServiceMockRecorder
}

// MockReportServiceMockRecorder is the mock recorder for MockReportService
type MockReportServiceMockRecorder struct {
	mock *MockReportService
}

// NewMockReportService creates a new mock instance
func NewMockReportService(ctrl *gomock.Controller) *MockReportService {
	mock := &MockReportService{ctrl: ctrl}
	mock.recorder = &MockReportServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockReportService) EXPECT() *MockReportServiceMockRecorder {
	return m.recorder
}

// CreateAuditTask mocks base method
func (m *MockReportService) CreateAuditTask(arg0 context.Context, arg1 bool, arg2 []*fintech_data.ReportBranch, arg3 *fintech_data.ReportGlobalConfig, arg4, arg5 int64, arg6, arg7 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAuditTask", arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAuditTask indicates an expected call of CreateAuditTask
func (mr *MockReportServiceMockRecorder) CreateAuditTask(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAuditTask", reflect.TypeOf((*MockReportService)(nil).CreateAuditTask), arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7)
}

// CreateTask mocks base method
func (m *MockReportService) CreateTask(arg0 context.Context, arg1 types.CreateTaskRequest) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTask", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTask indicates an expected call of CreateTask
func (mr *MockReportServiceMockRecorder) CreateTask(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTask", reflect.TypeOf((*MockReportService)(nil).CreateTask), arg0, arg1)
}
