// Code generated by MockGen. DO NOT EDIT.
// Source: go.easyops.local/fintech_data/internal/report_task (interfaces: ReportChecker)

// Package report_task is a generated GoMock package.
package report_task

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	fintech_data "go.easyops.local/contracts/protorepo-models/easyops/model/fintech_data"
)

// MockReportChecker is a mock of ReportChecker interface
type MockReportChecker struct {
	ctrl     *gomock.Controller
	recorder *MockReportCheckerMockRecorder
}

// MockReportCheckerMockRecorder is the mock recorder for MockReportChecker
type MockReportCheckerMockRecorder struct {
	mock *MockReportChecker
}

// NewMockReportChecker creates a new mock instance
func NewMockReportChecker(ctrl *gomock.Controller) *MockReportChecker {
	mock := &MockReportChecker{ctrl: ctrl}
	mock.recorder = &MockReportCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockReportChecker) EXPECT() *MockReportCheckerMockRecorder {
	return m.recorder
}

// TaskCheck mocks base method
func (m *MockReportChecker) TaskCheck(arg0 context.Context, arg1 *fintech_data.ReportTask, arg2 *fintech_data.ReportGlobalConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TaskCheck", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// TaskCheck indicates an expected call of TaskCheck
func (mr *MockReportCheckerMockRecorder) TaskCheck(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TaskCheck", reflect.TypeOf((*MockReportChecker)(nil).TaskCheck), arg0, arg1, arg2)
}
