// Code generated by MockGen. DO NOT EDIT.
// Source: go.easyops.local/fintech_data/internal/report_center (interfaces: Service)

// Package report_center is a generated GoMock package.
package report_center

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	fintech_data "go.easyops.local/contracts/protorepo-models/easyops/model/fintech_data"
	report_center "go.easyops.local/fintech_data/internal/report_center"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// Audit mocks base method.
func (m *MockService) Audit(arg0 context.Context, arg1 report_center.AuditRequest, arg2 *fintech_data.ReportGlobalConfig) (*report_center.AuditResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Audit", arg0, arg1, arg2)
	ret0, _ := ret[0].(*report_center.AuditResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Audit indicates an expected call of Audit.
func (mr *MockServiceMockRecorder) Audit(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Audit", reflect.TypeOf((*MockService)(nil).Audit), arg0, arg1, arg2)
}

// CheckReportResult mocks base method.
func (m *MockService) CheckReportResult(arg0 context.Context, arg1 report_center.CheckRequest, arg2 *fintech_data.ReportGlobalConfig) (*report_center.CheckResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckReportResult", arg0, arg1, arg2)
	ret0, _ := ret[0].(*report_center.CheckResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckReportResult indicates an expected call of CheckReportResult.
func (mr *MockServiceMockRecorder) CheckReportResult(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckReportResult", reflect.TypeOf((*MockService)(nil).CheckReportResult), arg0, arg1, arg2)
}

// GetToken mocks base method.
func (m *MockService) GetToken(arg0 context.Context, arg1 report_center.TokenRequest, arg2 *fintech_data.ReportGlobalConfig) (*report_center.TokenInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetToken", arg0, arg1, arg2)
	ret0, _ := ret[0].(*report_center.TokenInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetToken indicates an expected call of GetToken.
func (mr *MockServiceMockRecorder) GetToken(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetToken", reflect.TypeOf((*MockService)(nil).GetToken), arg0, arg1, arg2)
}

// ReportData mocks base method.
func (m *MockService) ReportData(arg0 context.Context, arg1 report_center.ReportRequest, arg2 *fintech_data.ReportGlobalConfig) (*report_center.ReportResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReportData", arg0, arg1, arg2)
	ret0, _ := ret[0].(*report_center.ReportResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReportData indicates an expected call of ReportData.
func (mr *MockServiceMockRecorder) ReportData(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReportData", reflect.TypeOf((*MockService)(nil).ReportData), arg0, arg1, arg2)
}

// SelectBranchId mocks base method.
func (m *MockService) SelectBranchId(arg0 context.Context, arg1 report_center.BranchIdRequest, arg2 *fintech_data.ReportGlobalConfig) (*report_center.BranchIdResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectBranchId", arg0, arg1, arg2)
	ret0, _ := ret[0].(*report_center.BranchIdResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectBranchId indicates an expected call of SelectBranchId.
func (mr *MockServiceMockRecorder) SelectBranchId(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectBranchId", reflect.TypeOf((*MockService)(nil).SelectBranchId), arg0, arg1, arg2)
}
