// Code generated by MockGen. DO NOT EDIT.
// Source: go.easyops.local/fintech_data/internal/fill_instance/dispatch (interfaces: Dispatcher)

// Package fill_instance is a generated GoMock package.
package fill_instance

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	fill_instance "go.easyops.local/fintech_data/internal/fill_instance"
)

// MockDispatcher is a mock of Dispatcher interface
type MockDispatcher struct {
	ctrl     *gomock.Controller
	recorder *MockDispatcherMockRecorder
}

// MockDispatcherMockRecorder is the mock recorder for MockDispatcher
type MockDispatcherMockRecorder struct {
	mock *MockDispatcher
}

// NewMockDispatcher creates a new mock instance
func NewMockDispatcher(ctrl *gomock.Controller) *MockDispatcher {
	mock := &MockDispatcher{ctrl: ctrl}
	mock.recorder = &MockDispatcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockDispatcher) EXPECT() *MockDispatcherMockRecorder {
	return m.recorder
}

// PushJob mocks base method
func (m *MockDispatcher) PushJob(arg0 context.Context, arg1 string, arg2 fill_instance.ProcessItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PushJob", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// PushJob indicates an expected call of PushJob
func (mr *MockDispatcherMockRecorder) PushJob(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PushJob", reflect.TypeOf((*MockDispatcher)(nil).PushJob), arg0, arg1, arg2)
}

// WakeUpJobs mocks base method
func (m *MockDispatcher) WakeUpJobs() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WakeUpJobs")
	ret0, _ := ret[0].(error)
	return ret0
}

// WakeUpJobs indicates an expected call of WakeUpJobs
func (mr *MockDispatcherMockRecorder) WakeUpJobs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WakeUpJobs", reflect.TypeOf((*MockDispatcher)(nil).WakeUpJobs))
}
