// Code generated by MockGen. DO NOT EDIT.
// Source: go.easyops.local/fintech_data/internal/fill_instance (interfaces: Service)

// Package fill_instance is a generated GoMock package.
package fill_instance

import (
	context "context"
	reflect "reflect"

	types "github.com/gogo/protobuf/types"
	gomock "github.com/golang/mock/gomock"

	fill_instance "go.easyops.local/fintech_data/internal/fill_instance"
)

// MockService is a mock of Service interface
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// FillInstance mocks base method
func (m *MockService) FillInstance(arg0 context.Context, arg1 string, arg2 []fill_instance.ProcessItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FillInstance", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// FillInstance indicates an expected call of FillInstance
func (mr *MockServiceMockRecorder) FillInstance(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FillInstance", reflect.TypeOf((*MockService)(nil).FillInstance), arg0, arg1, arg2)
}

// HasEffectedRule mocks base method
func (m *MockService) HasEffectedRule(arg0 context.Context, arg1 string, arg2 fill_instance.ProcessItem, arg3 *types.Struct) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasEffectedRule", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasEffectedRule indicates an expected call of HasEffectedRule
func (mr *MockServiceMockRecorder) HasEffectedRule(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasEffectedRule", reflect.TypeOf((*MockService)(nil).HasEffectedRule), arg0, arg1, arg2, arg3)
}

// RegisterSubscribers mocks base method
func (m *MockService) RegisterSubscribers() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterSubscribers")
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterSubscribers indicates an expected call of RegisterSubscribers
func (mr *MockServiceMockRecorder) RegisterSubscribers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterSubscribers", reflect.TypeOf((*MockService)(nil).RegisterSubscribers))
}
