// Code generated by MockGen. DO NOT EDIT.
// Source: go.easyops.local/agollo (interfaces: Client)

// Package agollo_client is a generated GoMock package.
package agollo_client

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	agollo "go.easyops.local/agollo"
)

// MockAgolloClient is a mock of Client interface.
type MockAgolloClient struct {
	ctrl     *gomock.Controller
	recorder *MockAgolloClientMockRecorder
}

// MockAgolloClientMockRecorder is the mock recorder for MockAgolloClient.
type MockAgolloClientMockRecorder struct {
	mock *MockAgolloClient
}

// NewMockAgolloClient creates a new mock instance.
func NewMockAgolloClient(ctrl *gomock.Controller) *MockAgolloClient {
	mock := &MockAgolloClient{ctrl: ctrl}
	mock.recorder = &MockAgolloClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgolloClient) EXPECT() *MockAgolloClientMockRecorder {
	return m.recorder
}

// GetAllKeys mocks base method.
func (m *MockAgolloClient) GetAllKeys(arg0 ...agollo.OpOption) []string {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAllKeys", varargs...)
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetAllKeys indicates an expected call of GetAllKeys.
func (mr *MockAgolloClientMockRecorder) GetAllKeys(arg0 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllKeys", reflect.TypeOf((*MockAgolloClient)(nil).GetAllKeys), arg0...)
}

// GetAndUnmarshalWithJson mocks base method.
func (m *MockAgolloClient) GetAndUnmarshalWithJson(arg0 string, arg1 interface{}, arg2 ...agollo.OpOption) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAndUnmarshalWithJson", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetAndUnmarshalWithJson indicates an expected call of GetAndUnmarshalWithJson.
func (mr *MockAgolloClientMockRecorder) GetAndUnmarshalWithJson(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAndUnmarshalWithJson", reflect.TypeOf((*MockAgolloClient)(nil).GetAndUnmarshalWithJson), varargs...)
}

// GetAndUnmarshalWithYaml mocks base method.
func (m *MockAgolloClient) GetAndUnmarshalWithYaml(arg0 string, arg1 interface{}, arg2 ...agollo.OpOption) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAndUnmarshalWithYaml", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetAndUnmarshalWithYaml indicates an expected call of GetAndUnmarshalWithYaml.
func (mr *MockAgolloClientMockRecorder) GetAndUnmarshalWithYaml(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAndUnmarshalWithYaml", reflect.TypeOf((*MockAgolloClient)(nil).GetAndUnmarshalWithYaml), varargs...)
}

// GetBool mocks base method.
func (m *MockAgolloClient) GetBool(arg0 string, arg1 bool, arg2 ...agollo.OpOption) bool {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetBool", varargs...)
	ret0, _ := ret[0].(bool)
	return ret0
}

// GetBool indicates an expected call of GetBool.
func (mr *MockAgolloClientMockRecorder) GetBool(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBool", reflect.TypeOf((*MockAgolloClient)(nil).GetBool), varargs...)
}

// GetContent mocks base method.
func (m *MockAgolloClient) GetContent(arg0 ...agollo.OpOption) string {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetContent", varargs...)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetContent indicates an expected call of GetContent.
func (mr *MockAgolloClientMockRecorder) GetContent(arg0 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContent", reflect.TypeOf((*MockAgolloClient)(nil).GetContent), arg0...)
}

// GetFloat mocks base method.
func (m *MockAgolloClient) GetFloat(arg0 string, arg1 float64, arg2 ...agollo.OpOption) float64 {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetFloat", varargs...)
	ret0, _ := ret[0].(float64)
	return ret0
}

// GetFloat indicates an expected call of GetFloat.
func (mr *MockAgolloClientMockRecorder) GetFloat(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFloat", reflect.TypeOf((*MockAgolloClient)(nil).GetFloat), varargs...)
}

// GetInt mocks base method.
func (m *MockAgolloClient) GetInt(arg0 string, arg1 int, arg2 ...agollo.OpOption) int {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetInt", varargs...)
	ret0, _ := ret[0].(int)
	return ret0
}

// GetInt indicates an expected call of GetInt.
func (mr *MockAgolloClientMockRecorder) GetInt(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInt", reflect.TypeOf((*MockAgolloClient)(nil).GetInt), varargs...)
}

// GetPropertiesContent mocks base method.
func (m *MockAgolloClient) GetPropertiesContent(arg0 ...agollo.OpOption) string {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetPropertiesContent", varargs...)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetPropertiesContent indicates an expected call of GetPropertiesContent.
func (mr *MockAgolloClientMockRecorder) GetPropertiesContent(arg0 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPropertiesContent", reflect.TypeOf((*MockAgolloClient)(nil).GetPropertiesContent), arg0...)
}

// GetReleaseKey mocks base method.
func (m *MockAgolloClient) GetReleaseKey(arg0 ...agollo.OpOption) string {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetReleaseKey", varargs...)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetReleaseKey indicates an expected call of GetReleaseKey.
func (mr *MockAgolloClientMockRecorder) GetReleaseKey(arg0 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReleaseKey", reflect.TypeOf((*MockAgolloClient)(nil).GetReleaseKey), arg0...)
}

// GetString mocks base method.
func (m *MockAgolloClient) GetString(arg0, arg1 string, arg2 ...agollo.OpOption) string {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetString", varargs...)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetString indicates an expected call of GetString.
func (mr *MockAgolloClientMockRecorder) GetString(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetString", reflect.TypeOf((*MockAgolloClient)(nil).GetString), varargs...)
}

// GetStringSlice mocks base method.
func (m *MockAgolloClient) GetStringSlice(arg0 string, arg1 []string, arg2 ...agollo.OpOption) []string {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetStringSlice", varargs...)
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetStringSlice indicates an expected call of GetStringSlice.
func (mr *MockAgolloClientMockRecorder) GetStringSlice(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStringSlice", reflect.TypeOf((*MockAgolloClient)(nil).GetStringSlice), varargs...)
}

// MustGetAndUnmarshalWithJson mocks base method.
func (m *MockAgolloClient) MustGetAndUnmarshalWithJson(arg0 string, arg1 interface{}, arg2 ...agollo.OpOption) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "MustGetAndUnmarshalWithJson", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// MustGetAndUnmarshalWithJson indicates an expected call of MustGetAndUnmarshalWithJson.
func (mr *MockAgolloClientMockRecorder) MustGetAndUnmarshalWithJson(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MustGetAndUnmarshalWithJson", reflect.TypeOf((*MockAgolloClient)(nil).MustGetAndUnmarshalWithJson), varargs...)
}

// MustGetAndUnmarshalWithYaml mocks base method.
func (m *MockAgolloClient) MustGetAndUnmarshalWithYaml(arg0 string, arg1 interface{}, arg2 ...agollo.OpOption) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "MustGetAndUnmarshalWithYaml", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// MustGetAndUnmarshalWithYaml indicates an expected call of MustGetAndUnmarshalWithYaml.
func (mr *MockAgolloClientMockRecorder) MustGetAndUnmarshalWithYaml(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MustGetAndUnmarshalWithYaml", reflect.TypeOf((*MockAgolloClient)(nil).MustGetAndUnmarshalWithYaml), varargs...)
}

// MustGetBool mocks base method.
func (m *MockAgolloClient) MustGetBool(arg0 string, arg1 ...agollo.OpOption) bool {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "MustGetBool", varargs...)
	ret0, _ := ret[0].(bool)
	return ret0
}

// MustGetBool indicates an expected call of MustGetBool.
func (mr *MockAgolloClientMockRecorder) MustGetBool(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MustGetBool", reflect.TypeOf((*MockAgolloClient)(nil).MustGetBool), varargs...)
}

// MustGetContent mocks base method.
func (m *MockAgolloClient) MustGetContent(arg0 ...agollo.OpOption) string {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "MustGetContent", varargs...)
	ret0, _ := ret[0].(string)
	return ret0
}

// MustGetContent indicates an expected call of MustGetContent.
func (mr *MockAgolloClientMockRecorder) MustGetContent(arg0 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MustGetContent", reflect.TypeOf((*MockAgolloClient)(nil).MustGetContent), arg0...)
}

// MustGetFloat mocks base method.
func (m *MockAgolloClient) MustGetFloat(arg0 string, arg1 ...agollo.OpOption) float64 {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "MustGetFloat", varargs...)
	ret0, _ := ret[0].(float64)
	return ret0
}

// MustGetFloat indicates an expected call of MustGetFloat.
func (mr *MockAgolloClientMockRecorder) MustGetFloat(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MustGetFloat", reflect.TypeOf((*MockAgolloClient)(nil).MustGetFloat), varargs...)
}

// MustGetInt mocks base method.
func (m *MockAgolloClient) MustGetInt(arg0 string, arg1 ...agollo.OpOption) int {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "MustGetInt", varargs...)
	ret0, _ := ret[0].(int)
	return ret0
}

// MustGetInt indicates an expected call of MustGetInt.
func (mr *MockAgolloClientMockRecorder) MustGetInt(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MustGetInt", reflect.TypeOf((*MockAgolloClient)(nil).MustGetInt), varargs...)
}

// MustGetString mocks base method.
func (m *MockAgolloClient) MustGetString(arg0 string, arg1 ...agollo.OpOption) string {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "MustGetString", varargs...)
	ret0, _ := ret[0].(string)
	return ret0
}

// MustGetString indicates an expected call of MustGetString.
func (mr *MockAgolloClientMockRecorder) MustGetString(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MustGetString", reflect.TypeOf((*MockAgolloClient)(nil).MustGetString), varargs...)
}

// MustGetStringSlice mocks base method.
func (m *MockAgolloClient) MustGetStringSlice(arg0 string, arg1 ...agollo.OpOption) []string {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "MustGetStringSlice", varargs...)
	ret0, _ := ret[0].([]string)
	return ret0
}

// MustGetStringSlice indicates an expected call of MustGetStringSlice.
func (mr *MockAgolloClientMockRecorder) MustGetStringSlice(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MustGetStringSlice", reflect.TypeOf((*MockAgolloClient)(nil).MustGetStringSlice), varargs...)
}

// OnUpdate mocks base method.
func (m *MockAgolloClient) OnUpdate(arg0 func(*agollo.ChangeEvent)) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnUpdate", arg0)
}

// OnUpdate indicates an expected call of OnUpdate.
func (mr *MockAgolloClientMockRecorder) OnUpdate(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnUpdate", reflect.TypeOf((*MockAgolloClient)(nil).OnUpdate), arg0)
}

// Start mocks base method.
func (m *MockAgolloClient) Start() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start")
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockAgolloClientMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockAgolloClient)(nil).Start))
}

// Stop mocks base method.
func (m *MockAgolloClient) Stop() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop")
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockAgolloClientMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockAgolloClient)(nil).Stop))
}

// SubscribeToNamespaces mocks base method.
func (m *MockAgolloClient) SubscribeToNamespaces(arg0 ...string) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SubscribeToNamespaces", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// SubscribeToNamespaces indicates an expected call of SubscribeToNamespaces.
func (mr *MockAgolloClientMockRecorder) SubscribeToNamespaces(arg0 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeToNamespaces", reflect.TypeOf((*MockAgolloClient)(nil).SubscribeToNamespaces), arg0...)
}
