// Code generated by giraffe-go. DO NOT EDIT.
package report_conf

import (
	"github.com/gin-gonic/gin"
	types "github.com/gogo/protobuf/types"

	message "go.easyops.local/contracts/protorepo-fintech_data/report_conf"
	"go.easyops.local/fintech_data/internal/apierrors"
	"go.easyops.local/fintech_data/report_conf/validators"
	"go.easyops.local/kit/gerr"
	kitweb "go.easyops.local/kit/web"
	"go.easyops.local/slog"
	logctx "go.easyops.local/slog/context"
)

var _ kitweb.JSONPb
var _ = apierrors.ErrInvalidArgument
var _ = types.Struct{}
var _ = validators.EmptyTree

type ReportConfController struct {
	logger  slog.Logger
	service ReportConfService
}

func NewReportConfController(logger slog.Logger, service ReportConfService) *ReportConfController {
	return &ReportConfController{
		logger:  logger,
		service: service,
	}
}

func (s *ReportConfController) UpdateMappingRule(ctx *gin.Context) {
	logger := logctx.MustGetLogger(ctx.Request.Context())
	var _ = logger
	var err error

	request, err := validators.ValidateUpdateMappingRule(ctx)
	if err != nil {
		apiError := gerr.ToApiError(err)
		ctx.JSON(apiError.Status(), apiError.Data())
		return
	}

	data, err := s.service.UpdateMappingRule(ctx.Request.Context(), request)
	if err != nil {
		apiError := gerr.ToApiError(err)
		ctx.JSON(apiError.Status(), apiError.Data())
		return
	} else {

		ctx.Render(200, kitweb.JSONPb{
			Data: &message.UpdateMappingRuleResponseWrapper{
				Data: data,
			},
			UseCustomMarshaler: true,
			UseGogo:            true,
		})
		return

	}
}

func (s *ReportConfController) UpdateReportConf(ctx *gin.Context) {
	logger := logctx.MustGetLogger(ctx.Request.Context())
	var _ = logger
	var err error

	request, err := validators.ValidateUpdateReportConf(ctx)
	if err != nil {
		apiError := gerr.ToApiError(err)
		ctx.JSON(apiError.Status(), apiError.Data())
		return
	}

	data, err := s.service.UpdateReportConf(ctx.Request.Context(), request)
	if err != nil {
		apiError := gerr.ToApiError(err)
		ctx.JSON(apiError.Status(), apiError.Data())
		return
	} else {

		ctx.Render(200, kitweb.JSONPb{
			Data: &message.UpdateReportConfResponseWrapper{
				Data: data,
			},
			UseCustomMarshaler: true,
			UseGogo:            true,
		})
		return

	}
}
