// Code generated by giraffe-go. DO NOT EDIT.
package report_conf

import "github.com/gin-gonic/gin"

func (s *ReportConfController) Register(engine *gin.Engine) {
	engine.PUT("/api/mapping/rule/:instanceId", s.UpdateMappingRule)
	engine.PUT("/api/report/conf/:instanceId", s.UpdateReportConf)
}
