// Code generated by giraffe-go. DO NOT EDIT.
package report_conf

import (
	message "go.easyops.local/contracts/protorepo-fintech_data/report_conf"

	"context"
	"io"
	"mime/multipart"

	"github.com/gin-gonic/gin/render"
	types "github.com/gogo/protobuf/types"

	"go.easyops.local/contracts/protorepo-models/easyops/model/fintech_data"
)

var _ = render.WriteJSON
var _ = multipart.NewReader
var _ = io.Copy
var _ = types.Struct{}
var _ = message.NewClient

type ReportConfService interface {
	UpdateMappingRule(ctx context.Context, request *fintech_data.ReportObjectConf) (*message.UpdateMappingRuleResponse, error)
	UpdateReportConf(ctx context.Context, request *fintech_data.ReportObjectConf) (*message.UpdateReportConfResponse, error)
}
