// Code generated by MockGen. DO NOT EDIT.
// Source: go.easyops.local/contracts/protorepo-monthly_collection_service/document (interfaces: Client)

// Package monthly is a generated GoMock package.
package monthly

import (
	context "context"
	reflect "reflect"

	types "github.com/gogo/protobuf/types"
	gomock "github.com/golang/mock/gomock"
	document "go.easyops.local/contracts/protorepo-monthly_collection_service/document"
)

// MockCollectionClient is a mock of Client interface.
type MockCollectionClient struct {
	ctrl     *gomock.Controller
	recorder *MockCollectionClientMockRecorder
}

// MockCollectionClientMockRecorder is the mock recorder for MockCollectionClient.
type MockCollectionClientMockRecorder struct {
	mock *MockCollectionClient
}

// NewMockCollectionClient creates a new mock instance.
func NewMockCollectionClient(ctrl *gomock.Controller) *MockCollectionClient {
	mock := &MockCollectionClient{ctrl: ctrl}
	mock.recorder = &MockCollectionClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCollectionClient) EXPECT() *MockCollectionClientMockRecorder {
	return m.recorder
}

// BatchCreate mocks base method.
func (m *MockCollectionClient) BatchCreate(arg0 context.Context, arg1 *document.BatchCreateRequest) (*document.BatchCreateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchCreate", arg0, arg1)
	ret0, _ := ret[0].(*document.BatchCreateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchCreate indicates an expected call of BatchCreate.
func (mr *MockCollectionClientMockRecorder) BatchCreate(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchCreate", reflect.TypeOf((*MockCollectionClient)(nil).BatchCreate), arg0, arg1)
}

// Create mocks base method.
func (m *MockCollectionClient) Create(arg0 context.Context, arg1 *document.CreateRequest) (*document.CreateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(*document.CreateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockCollectionClientMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCollectionClient)(nil).Create), arg0, arg1)
}

// FindIDs mocks base method.
func (m *MockCollectionClient) FindIDs(arg0 context.Context, arg1 *document.FindIDsRequest) (*document.FindIDsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindIDs", arg0, arg1)
	ret0, _ := ret[0].(*document.FindIDsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindIDs indicates an expected call of FindIDs.
func (mr *MockCollectionClientMockRecorder) FindIDs(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindIDs", reflect.TypeOf((*MockCollectionClient)(nil).FindIDs), arg0, arg1)
}

// GET mocks base method.
func (m *MockCollectionClient) GET(arg0 context.Context, arg1 *document.GETRequest) (*types.Struct, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GET", arg0, arg1)
	ret0, _ := ret[0].(*types.Struct)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GET indicates an expected call of GET.
func (mr *MockCollectionClientMockRecorder) GET(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GET", reflect.TypeOf((*MockCollectionClient)(nil).GET), arg0, arg1)
}

// Limit mocks base method.
func (m *MockCollectionClient) Limit(arg0 context.Context, arg1 *document.LimitRequest) (*document.LimitResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Limit", arg0, arg1)
	ret0, _ := ret[0].(*document.LimitResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Limit indicates an expected call of Limit.
func (mr *MockCollectionClientMockRecorder) Limit(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Limit", reflect.TypeOf((*MockCollectionClient)(nil).Limit), arg0, arg1)
}

// PushValueToList mocks base method.
func (m *MockCollectionClient) PushValueToList(arg0 context.Context, arg1 *document.PushValueToListRequest) (*types.Empty, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PushValueToList", arg0, arg1)
	ret0, _ := ret[0].(*types.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PushValueToList indicates an expected call of PushValueToList.
func (mr *MockCollectionClientMockRecorder) PushValueToList(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PushValueToList", reflect.TypeOf((*MockCollectionClient)(nil).PushValueToList), arg0, arg1)
}

// Search mocks base method.
func (m *MockCollectionClient) Search(arg0 context.Context, arg1 *document.SearchRequest) (*document.SearchResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", arg0, arg1)
	ret0, _ := ret[0].(*document.SearchResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockCollectionClientMockRecorder) Search(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockCollectionClient)(nil).Search), arg0, arg1)
}

// SearchByIds mocks base method.
func (m *MockCollectionClient) SearchByIds(arg0 context.Context, arg1 *document.SearchByIdsRequest) (*document.SearchByIdsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchByIds", arg0, arg1)
	ret0, _ := ret[0].(*document.SearchByIdsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchByIds indicates an expected call of SearchByIds.
func (mr *MockCollectionClientMockRecorder) SearchByIds(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchByIds", reflect.TypeOf((*MockCollectionClient)(nil).SearchByIds), arg0, arg1)
}

// Update mocks base method.
func (m *MockCollectionClient) Update(arg0 context.Context, arg1 *document.UpdateRequest) (*types.Empty, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(*types.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockCollectionClientMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCollectionClient)(nil).Update), arg0, arg1)
}
